### PR TITLE
fix: display default header in additional months

### PR DESCRIPTION
**Pull request by Zertz**
This is a quick fix to test things out manually on my end, I'll clean up related code and update automated tests shortly.

Related to #1721

### CODE REVIEW

**Comment by lironezra** [comment]
Hi Zertz, 
Any update on that? did you add something to achieve that functionality? 
I have just tried to display two month calendars with custom header for both and it's not seems to works...

Thanks a lot!

**Comment by Zertz** [comment]
Hey, I ended up [creating a fork](https://github.com/Zertz/react-d8picker) because I stumbled upon quite a few blockers for our particular use case.

It's still a work in progress but the general idea was to dramatically reduce the number of props by switching to render props.

**Comment by lironezra** [comment]
Hi,

Do you have any estimation about it? 

Thank you!

**Comment by Zertz** [comment]
Probably sometimes in December but keep in mind there is no migration path. It will do a lot less out of the box and most customization will be done through render props instead.

**Comment by lironezra** [comment]
Hi Zertz,

Just to make things clear,  are you planning on adding this feature / fix to the original repository as well ?

**Comment by Zertz** [comment]
Yes.

**Comment by Zertz** [comment]
It turned out to be trickier than I thought, so unfortunately I won't.

**Pull request closed without merging**
