### PR TITLE
Allow React 18 peer dep

### PR DESCRIPTION
**Pull request by jonasws**

### CODE REVIEW

**Comment by noudadrichem** [comment]
This would be nice!

**Comment by Johann-S** [comment]
Maybe if we ping one of the mainteners @martijnrusschen 🙏

**Comment by DoodleBobBuffPants** [comment]
+1

**Comment by rivajunior** [comment]
1 test is failing

image

**Comment by martijnrusschen** [comment]
Sorry for the delay on this. The failing test seems unrelated but I'd love to get that fixed. If someone has time to look into that I'd really appreciate it!

**Comment by joshkautz** [comment]
New to the project but going to dig it to try to help resolve. Important to get this working with React ^18.1.0

**Comment by martijnrusschen** [comment]
Merging in the latest master branch should fix the build for this pull request.

**Pull request closed without merging**
