### PR TITLE
Hide keyboard-selection highlighting in inline mode

### PR DESCRIPTION
**Pull request by gavacho**
Fixes https://github.com/Hacker0x01/react-datepicker/issues/745

### CODE REVIEW

**Comment by gavacho** [comment]
not sure how to get the checks to pass

**Comment by martijnrusschen** [comment]
Merging this to get people unblocked.

**Comment by martijnrusschen** [comment]
Thanks for looking into this @gavacho!

**Comment by rafeememon** [comment]
Thanks @gavacho.  Would you be able to add a test case for this as well?

**Pull request merged**
