### PR TITLE
remove inline check for keyboard selected

### PR DESCRIPTION
**Pull request by arsnyder16**
When using an inline date picker, you can navigate the days with the keyboard but they do not style correctly so it doesn't appear that it is working

### CODE REVIEW

**Comment by arsnyder16** [comment]
#2141

**Comment by arsnyder16** [comment]
#2141

**Comment by arsnyder16** [comment]
#1541  
#1337

**Comment by arsnyder16** [comment]
@martijnrusschen Any idea why the inline check was there ?

**Comment by arsnyder16** [comment]
@martijnrusschen  Any feedback would be appreciated.  Waiting for this to fix #2141

**Comment by martijnrusschen** [comment]
I didn't check this yet since the build was broken. Can you check what's going wrong?

**Comment by arsnyder16** [comment]
@martijnrusschen  Sure its just a test that is checking the exact condition that i am removing,but there doesn't seem to be any indication to why the check is needed. It looks more like the test was just written based on the logic not for any specific use case

**Comment by arsnyder16** [comment]
@martijnrusschen I went ahead and just updated the test. All green.

**Comment by arsnyder16** [comment]
@martijnrusschen Any update here?

**Pull request merged**
