### PR TITLE
Add the ability to show week numbers on the calendar.

### LINKED ISSUE #420: Display weeknumber
I would love to see week numbers in the calender :smile:

### PR DESCRIPTION
**Pull request by MarkReeder**
Fixes #420 

screen shot 2016-10-03 at 9 05 56 pm

### CODE REVIEW

**Comment by rafeememon** [comment]
This looks great -- a couple things:

* Please remove the docs update from the PR; those are generated automatically when we release
* Can we get some tests on this guy? =)

**Comment by MarkReeder** [comment]
@rafeememon sure thing- just to confirm on the docs, just `docs-site/bundle.js` should be removed, correct? Also, happy to add a some tests.

**Comment by rafeememon** [comment]
@MarkReeder correct; and thanks!

**Comment by martijnrusschen** [comment]
@rafeememon Anymore comments on this?

**Comment by martijnrusschen** [comment]
Hi @MarkReeder, 

This looks good to go. I had some issues merging the branch to master since `src/calendar.jsx` is conflicting. Could you update your PR so I can merge this ASAP?

**Comment by MarkReeder** [comment]
@martijnrusschen I've rebased against the current master- let me know if you need anything else.

**Pull request merged**
