### PR TITLE
fix #198: Updated to react 0.14

### LINKED ISSUE #198: Peer dependencies for React 0.14
Hi,

I have updated my app to React 0.14 and I get a `peerDependencies` error. I have tried running `react-datepicker` with React 0.14 and it works fine except for some warnings. Do you need help to update the package to work with the new React 0.14 api?

Most of the warnings are related to `react-dom`:

```
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.warning @ warning.js:45newFn @ deprecated.js:32r.createClass._renderPopover @ react-datepicker.min.js:1r.createClass.componentDidMount @ react-datepicker.min.js:1assign.notifyAll @ CallbackQueue.js:65ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactPerf.measure.wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:94ReactEventListener.dispatchEvent @ ReactEventListener.js:204
warning.js:45 Warning: Popover.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.warning @ warning.js:45ReactBrowserComponentMixin.getDOMNode @ ReactBrowserComponentMixin.js:30r.createClass._tetherOptions @ react-datepicker.min.js:1r.createClass._renderPopover @ react-datepicker.min.js:1r.createClass.componentDidMount @ react-datepicker.min.js:1assign.notifyAll @ CallbackQueue.js:65ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactPerf.measure.wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:94ReactEventListener.dispatchEvent @ ReactEventListener.js:204
warning.js:45 Warning: React.unmountComponentAtNode is deprecated. Please use ReactDOM.unmountComponentAtNode from require('react-dom') instead.
```

Cheers,
Arnaud

### PR DESCRIPTION
**Pull request by arnaudbenard**
I updated to React 0.14, all the tests pass.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Nice start, according to the issue you noted a few warnings:

- Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom')
- Warning: Popover.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance)
- Warning: React.unmountComponentAtNode is deprecated. Please use ReactDOM.unmountComponentAtNode from require('react-dom') instead. 

Looking at your code it looks like the first two warnings are fixed. Do you have any plans to fix the other warning as well?

**Comment by arnaudbenard** [comment]
The last one isn't covered by the tests, I discovered it by using the lib in my app. I can fix it if you want to, no problem :)

**Comment by martijnrusschen** [comment]
Would be cool, I can merge it when you're ready!

**Comment by arnaudbenard** [comment]
done!

**Pull request merged**
