### PR TITLE
Fixed down year arrow for rtl layout

### PR DESCRIPTION
**Pull request by salmankhann**
The down arrow for the year in RTL was overlapping with the text, just fixed its layout

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you add a screenshot on how this looks like?

**Comment by rafeememon** [comment]
@salmanhoque, please include a screenshot of before and after the fix

**Comment by salmankhann** [comment]
This is how it looks. FYI you tagged the wrong guy 😆 

screen shot 2016-08-07 at 12 01 06 pm

**Comment by martijnrusschen** [comment]
If someone has time to fix the build, I can merge this ASAP.

**Comment by martijnrusschen** [comment]
@salmankhann If you can fix the build, I can merge this for you.

**Comment by martijnrusschen** [comment]
Closing due inactivity.

**Pull request closed without merging**
