### PR TITLE
Add portal overlay for datepicker

### PR DESCRIPTION
**Pull request by ro-savage**
This PR adds a new prop which creates a Portal/Overlay version of the calendar, and fixes issue #695 

This helps if the calendar is being used by a mobile device, or other small screen.

If the prop `withPortal` is passed, it will create a portal version of the calendar.

Example:
```js
<DatePicker
selected={this.state.startDate}
onChange={this.handleChange}
withPortal />
```

The docs have been updated. No tests have been updated as this did not affect any, and no new tests added as the logic is very straight forward.

Happy to hear feedback/changes.

### CODE REVIEW

**Comment by rafeememon** [comment]
I'm pretty skeptical of introducing a new dependency for this; unfortunately I don't think this should be included.  @martijnrusschen thoughts?

**Comment by ro-savage** [comment]
`react-portal` is the same module `react-dates` uses to create their portal. 

The alternative I had originally played with was to create a div/portal that contained the calendar set to `display: none;` then apply a new class when the calendar was opened that made the div visible.

This has a few issues that I didn't get around to resolving but nothing that looked like a show stopper. However, when I ran into them I checked the code for airbnb's dates module and saw they used react-portal. So decided to run with that encase there was more edge cases I wasn't aware off.

**Comment by ro-savage** [comment]
I have created PR #698 which removes the dependancy.

**Comment by rafeememon** [comment]
Closing in favor of #698

**Pull request closed without merging**
