### PR TITLE
Decouple keyboard selection from actual selection

### PR DESCRIPTION
**Pull request by github1**
This PR modifies the way keyboard navigation/selection works by separating the date which has been navigated to via the keyboard interface from the selected date of the component itself. The selected date (of the component) is only set/updated if the 'Enter' key is pressed.

- Introduces ```preSelection``` state variable holding keyboard position
  prior to confirmation of selection
- Sets/confirms the actual selection on ```Enter``` key press (fires the change event)
- When focused on the date input, pressing any arrow key opens the calendar for selection
- Prevents keyboard selection if ```date_utils::isDayDisabled``` evaluates to true
- Adds ```--keyboard-selected``` style modifier for ```preSelected``` date (the
  date selected via keyboard interface)

### CODE REVIEW

**Comment by bcullman** [comment]
This might fix #699

**Comment by martijnrusschen** [comment]
@github1 Before I can merge this, it would be awesome if you could rebase your PR with the latest master branch to make sure this can be merged.

**Comment by github1** [comment]
@martijnrusschen Thanks. The PR has been rebased.

**Comment by bcullman** [comment]
This does indeed fix #699

**Comment by martijnrusschen** [comment]
Thanks a lot!

**Pull request merged**
