### PR TITLE
Change calendar class to be more specific

### PR DESCRIPTION
**Pull request by rafeememon**
Re #387

Change the class name of the calendar component from `datepicker` to `datepicker__calendar` to help avoid potential naming conflicts.

### CODE REVIEW

**Comment by dmnd** [comment]
This works for me :+1:

**Comment by martijnrusschen** [comment]
Not sure about this. If you look at the way BEM CSS works, you should have a root class that's used like we do now. Getting rid of that makes the CSS less BEM'ish. Can't we change the classes to something more specific for this component instead?

**Comment by martijnrusschen** [comment]
Something like `.react-datepicker`?

**Comment by rafeememon** [comment]
Isn't the block `datepicker` and element `calendar`, like most of the components are styled now?  I think this change at least makes it more consistent with that style.

**Comment by rafeememon** [comment]
Thinking about this a little more, the change does remove the `.datepicker` top-level element, but technically the calendar doesn't nest in the element -- it's appended to `<body>` with the tethering library.  Also, I don't think we should limit ourselves to having a wrapper `div` with the `datepicker` class as this sets us up to have the top level element be the `input` instead.

**Comment by martijnrusschen** [comment]
I think the problem is 2-sided:
1.  I think we should try to wrap all our classes with a specific prefix for our component. This avoids any potential override issues. For example, `datepicker` we have here, but also `close-icon` are easily overwrite-able where this shouldn't happen by default.
2. We should try to maintain a "block" class as the base class for this component. We can debate what the block is. The current `datepicker` class is probably the the best candidate, but I agree that it's not 100% correct. (for example, the input isn't an element of the datepicker block.)

**Comment by rafeememon** [comment]
1. Definitely agree that all classes should be prefixed with `datepicker`.  The `close-icon` class is sadness that we should fix.  =P
2. I see what you mean, but take a look at my comment right before yours.  I think it would be great to have it possible for the `input` to be the top-level element to integrate with forms as seamlessly as possible.  Some styles in common libraries (bootstrap, elemental) look for inputs to be immediate children of certain elements, but forcing the datepicker to be wrapped in a div makes it impossible to work with this without nasty custom styling.

**Comment by martijnrusschen** [comment]
What about:
- react-datepicker
  - react-datepicker__input
    - possible child classes
  - react-datepicker__calendar
    - children 

Trying to figure out the best structure on solving this and moving forward.. Still have the wrapper div this way, lets try to iterate and find the best solution.

**Comment by martijnrusschen** [comment]
Or we introduce to 2 level classes:
- react-datepicker-input
- react-datepicker-calendar

**Comment by rafeememon** [comment]
Two levels is probably the way to go (since the calendar will not nested), but we probably won't need a `react-datepicker-input` class if it's just an `<input>` element.  In fact I think we should *not* provide styling for the `<input>` element so that it can integrate with forms as easily as possible.

**Comment by dmnd** [comment]
> I think we should not provide styling for the `<input>` element so that it can integrate with forms as easily as possible

:+1: That sounds great to me.

**Comment by rafeememon** [comment]
Continuing on #391, #396

**Pull request closed without merging**
