### PR TITLE
Upgrade react-popper to 0.8.2

### PR DESCRIPTION
**Pull request by martijnrusschen**

### CODE REVIEW

**Comment by Kerumen** [comment]
@martijnrusschen Thanks for the change! Can you cut a new release? `react-popper@0.7.5` as a big perf issue `react-datepicker` is currently resolving this.

**Comment by jsouthern-ngs** [comment]
@martijnrusschen. do you have an idea of when you'd push a release with the popper upgrade. we are working on an early march release that uses the picker. if you are waiting to compile more things into a release, we may go ahead and fork and update to meet this release date, and switch back when the next release is dropped.

**Comment by rafeememon** [comment]
@jsouthern-ngs, you should never be blocked on a release since you can easily unblock by forking the repo.

**Comment by jsouthern-ngs** [comment]
understood. we aren't blocked. i realize we can fork and pull from your origin at anytime.

**Comment by martijnrusschen** [comment]
Just pushed a release. Version 1.2.1 should have all changes included.

**Pull request merged**
