### PR TITLE
Month change callback + force show month navigation

### PR DESCRIPTION
**Pull request by intpp**
* forceShowNavigation - allow to show navigation between month when "includeDates" disable it.
* onMonthChange - call when month changed

### CODE REVIEW

**Comment by valdemars** [comment]
Will be useful for month navigation

**Comment by dutchakdev** [comment]
+

**Comment by intpp** [comment]
@martijnrusschen Why you ignore my PR?

**Comment by martijnrusschen** [comment]
Thanks!

**Pull request merged**
