### PR TITLE
Feature/2003  a11y enhancements

### PR DESCRIPTION
**Pull request by dan-diaz**
The following PR contains some updates intended to enhance accessibility.

What changed:

**Navigating the calendar with arrows now occurs inside the calendar, instead of in the input.**
This means that the focus is directly on the day, allowing screen readers to read aria labels.
This also frees up ArrowLeft and ArrowRight while focused on the input, so you can move your cursor across the text

**Tabbing inside the popper is looped, by default**
We're treating the popper more like a dialog as described in the W3C spec.
If you tab to the last focusable element in the popper, tabbing again will send you to the first element.
If you tab to the first focusable element in the popper, SHIFT tab will send you to the last element.
Escape will close the dialog and return focus to the input.

**Space and Enter will select a day**
Now that we apply focus directly to the Day in the calendar, Space and Enter select that day.

Please refer to the W3C spec if any of this sounds funky.
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

Addressing these items:
https://github.com/Hacker0x01/react-datepicker/issues/2003
https://github.com/Hacker0x01/react-datepicker/issues/2007
https://github.com/Hacker0x01/react-datepicker/issues/2008

### CODE REVIEW

**Comment by ben-caplan** [comment]
Any chance we can get this reviewed @martijnrusschen, @RSO, @rice, @alex-bekker?

**Comment by smcnulty0227** [comment]
Really looking forward to this PR getting merged to make react-datepicker awesomely accessible!

**Comment by ben-caplan** [comment]
I just wanted to bump this thread again so that it does not get stale. We would be happy to set up a conference call/screen share to walk through the changes and take realtime feedback to help get this process moving. Thoughts @martijnrusschen? 

Also @aij I see that @martijnrusschen mentioned having you take a look at the other open A11y PR. Any chance you want to give this a once over to help get this enhancement rolled out asap?

**Comment by martijnrusschen** [comment]
Thanks for this! Great to see this being improved and happy to get this merged and released. Two small things:
1. There's a merge conflict, can you help me get this fixed?
2. The test coverage on the changes is not great, any chance we can get that improved a bit?

**Comment by ben-caplan** [comment]
> Thanks for this! Great to see this being improved and happy to get this merged and released. Two small things:
> 
> 1. There's a merge conflict, can you help me get this fixed?
> 2. The test coverage on the changes is not great, any chance we can get that improved a bit?

Thanks for the feedback @martijnrusschen! @dan-diaz can you check on those merge conflicts ASAP? With regards to the code coverage, would it be possible to guide us a bit on what you feel is missing coverage? I know Dan removed a repetitive test as well as a test that was no longer applicable, but also added some new tests to extend coverage. Is there a particular case or util that is not being covered that we can help to cover?

**Comment by martijnrusschen** [comment]
Are you able to access this coverage report: https://codecov.io/gh/Hacker0x01/react-datepicker/compare/333270578cdc1cb7b91c24e1028e957f5b581ffd...b4bfb00937ac43b8ef43a88740a0197111eb89c2/changes.

**Comment by ben-caplan** [comment]
I am, but am not clear on what exactly this report says/means or what updates should be made to address?

**Comment by ben-caplan** [comment]
Amazing, thanks so much for your help with this @martijnrusschen

**Pull request merged**
