### PR TITLE
ShortMonth on MonthDropdown

### PR DESCRIPTION
**Pull request by marioramva**
For this to work I added prop useShortMonthInDropdown in DatePicker & MonthDropdown components
Also added the function getMonthShortInLocale in date_utils and the conditional in Calendar component

Finally added a className for selected option on both Month & Year Dropdown selected option. This only for css customization, because can't format parent based on child options.

### CODE REVIEW

**Comment by marioramva** [comment]
On reference to Issue #1183

**Comment by martijnrusschen** [comment]
Can you add some tests to make sure these changes are covered?

**Comment by marioramva** [comment]
I don't know how to perform tests on this project. 

I've imported it to my React project and the changes work as expected.

How can I test on this project?

**Comment by marioramva** [comment]
This is my CSS customized version of the plugin:
screen shot 2017-12-27 at 17 17 55

And this is the month dropdown with short month names:
screen shot 2017-12-27 at 17 18 10

**Comment by martijnrusschen** [comment]
There's a tests folder in the project. You can run these tests locally by running `yarn test`.

**Comment by martijnrusschen** [comment]
Can you please resolve the merge conflicts so that I can cleanly merge this PR?

**Pull request merged**
