### PR TITLE
no more this.refs

### PR DESCRIPTION
**Pull request by relifeted**
change ref to official usage: https://facebook.github.io/react/docs/refs-and-the-dom.html

### CODE REVIEW

**Comment by lbelinsk** [comment]
I am waiting for this pr to be merged because of react-modal problem with additional components that have this ref style.

https://github.com/reactjs/react-modal/issues/472

**Comment by martijnrusschen** [comment]
Looks like a nice improvement, but the build is still failing so can't merge this PR currently.

**Comment by relifeted** [comment]
Finally got some time to fix test case, plz review it, tks!

**Comment by rijk** [comment]
When will this update be released to npm?

**Comment by martijnrusschen** [comment]
Will do one now!

**Pull request merged**
