### PR TITLE
Make usable without globals

### PR DESCRIPTION
**Pull request by jbrumwell**
This PR makes it possible to require the plugin without have globals defined

### CODE REVIEW

**Comment by RSO** [comment]
Could you elaborate as to why you closed the pull request? I'd be interested in landing something that fixes this, if I can find a proper way to make it work in all cases.

**Comment by jbrumwell** [comment]
I still had some work I needed to do on. Can you elaborate on the use cases you need to support?

**Comment by RSO** [comment]
Well, at HackerOne we're still not up and running with modules, so for that we still need a file that compiles and sets the `DatePicker` variable on the `window`.

I would be perfectly fine with this file being generated as a separate `react-date-picker-global.js` or even as part of a separate repo, it's just that I couldn't find a clean/simple way to do this without `React` and `Tether` being compiled in that file as well.

So, I would like to have a file, that holds all datepicker-specific stuff, without having all the external dependencies compiled inside of it. Does this help?

**Comment by jbrumwell** [comment]
Yeah should be fairly easy to achieve, I'll take a look this weekend if I get time

**Pull request closed without merging**
