### PR TITLE
#2846, changed condition for renderCustomHeader with showTimeSelect prop

### PR DESCRIPTION
**Pull request by enflaer**
Condition for renderCustomHeader with showTimeSelect prop was changed, now it works correctly.

Changes are [here](https://github.com/enflaer/react-datepicker/commit/6b8540a753144a3e4323dc0b54aec3fb55ad2aa8#diff-ba0a2548ba8e373159fbf38d080f9db8c4738205898b7357963178048223dc70R687-R691), other things are linting.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you rebase this with the most recent master?

**Comment by enflaer** [comment]
@martijnrusschen branch is even with master. Or i don't understand what you want?

**Comment by enflaer** [comment]
@martijnrusschen done.

**Comment by liliwei25** [comment]
hi @enflaer, does this PR solve this issue? https://github.com/Hacker0x01/react-datepicker/issues/2765

**Comment by enflaer** [comment]
@martijnrusschen is something prevents merge this PR?

**Comment by martijnrusschen** [comment]
It would be great to add a test so that this doesn't break again. Would you be able to add that?

**Comment by enflaer** [comment]
> It would be great to add a test so that this doesn't break again. Would you be able to add that?

Ok, try to do that on this week.

**Comment by enflaer** [comment]
@martijnrusschen added [test case](https://github.com/Hacker0x01/react-datepicker/pull/2874/commits/a6e5053a246b83d154603909ad60596ed280af81#diff-4564514bd613cd13b36e0d93f9e636f4e331019ac7e234c6b12912344b5b1141R509) for it. Merged with actual master.

**Comment by enflaer** [comment]
@martijnrusschen added [test case](https://github.com/Hacker0x01/react-datepicker/pull/2874/commits/a6e5053a246b83d154603909ad60596ed280af81#diff-4564514bd613cd13b36e0d93f9e636f4e331019ac7e234c6b12912344b5b1141R509) for it. Merged with actual master.

**Comment by martijnrusschen** [comment]
v3.8.0 has been released a few minutes ago.

**Pull request merged**
