### PR TITLE
Change selection of inline picker. fix #927.

### LINKED ISSUE #927: Datepicker don't switch to new range in inline mode
Hi! I faced with a problem that I use DatePicker across the site and in one place I need it just for showing a quarter of year like the calendar.
Steps to reproduce:
1. Add inline datepicker
2. Change selected date (or min max dates like in my example)
3. Expect to switch calendar to the new range but it works just after click somewhere on the page.

I try to find own solution and I think it relates to #743 
But it strange that after click somewhere it works fine. Could I somehow forceUpdate datepicker to implicitly call `setOpen()` or whatever what makes it work :)

Here is the link to screencast of issue -> http://take.ms/oSAc8

I show the debugger statement that doesn't fire after the last click.

Thank you.

### PR DESCRIPTION
**Pull request by m1n0s**
Also remove semicolon by eslint checking.

fixes #927

### CODE REVIEW

**Comment by m1n0s** [comment]
Hi @martijnrusschen!
I kindly ask you to check this PR as soon as you can and release it because my project is very depending now on this feature.

I hope I've done check and updating state in proper place and it not - I hope you get the idea and can do it better.

Anyway thank you a lot for this awesome and very flexible picker.

**Comment by martijnrusschen** [comment]
Any chance we can add a regression test to avoid breaking this again?

**Comment by rafeememon** [comment]
I think this definitely needs a test, @m1n0s if you need to use this immediately you can build your forked repo and use that in your project.

**Comment by m1n0s** [comment]
@martijnrusschen @rafeememon 
I've added test case for my changes. Please review.

Leo

**Pull request merged**
