### PR TITLE
Add second css file for CSS Modules

### PR DESCRIPTION
**Pull request by ro-savage**
This PR adds in the creation of a second css file aimed at people using CSS Modules.

It applies the `:global` flag to all css in `react-datepicker`.

We simply import whatever changes are made to `datepicker.scss`, so there shouldn't be any change to future development.

```sass
:global {
  @import "datepicker";
}
```

This allows people using css modules to `require('import 'react-datepicker/dist/react-datepicker-cssmodules.css'')` and should work as expected.

There are other ways to handle CSS Modules, but this was an easy and quick solution.

### CODE REVIEW

**Comment by ro-savage** [comment]
The changes to `docs-site/bundle.js` and `docs-site/style.css` occur when running a npm run build.

I can remove them and rebase, but it will mean anytime someone does a build in future they will show two modified files in git.

**Comment by martijnrusschen** [comment]
Nice work, thanks!

**Comment by omjokine** [comment]
@martijnrusschen are you planning to release this?

**Comment by martijnrusschen** [comment]
I can release later today.

**Comment by flanamacca** [comment]
Has this been released?

**Comment by kushalmahajan** [comment]
Is there an example of this working somewhere via webpack loaders?

**Pull request merged**
