### PR TITLE
feat(Navigation) SA/ Improve UX and the ability to customize on navigation icons

### PR DESCRIPTION
**Pull request by ScottAgirs**
Hey fellas, 

First I will take this chance to thank y'all for this awesome package, been using for many years and I'm stoked to finally contribute.

This one is a topic that has been been a pain point since day one.
I have also come across countless questions on Stackoverflow and elsewhere with people asking for help solving this, so, hopefully, this helps some people out and adds some real value.

# The problem

The current default navigation icons are not ideal for the below reasons (potentially amongst others):
- they are small and outdated (a11y and UX has evolved a lot in the last few years and finger-friendly buttons do matter)
- customizing spacing/icons itself can be challenging because the button is the actual icon.

# The solution
If this is merged, the navigation button will contain a new intermediary element - `<span />`.
This will enable a user to do the following:
- control the spacing of the clickable button
- edit the nested `span::before` styles to fine-tune the feel and look of the controls.

## Testing
After reviewing the current tests, the changes made with this PR should not require new tests.

### Manual testing
I have manually tested and reviewed all styles and all implementations and made tweaks where necessary.

## A11y
The a11y markup has not been affected.

### Summary

I hope this is useful and would love to see this merged in - I know I will benefit for sure, and I`m sure (I hope) others will too.

Cheers |1ackers! : )

### CODE REVIEW

**Comment by martijnrusschen** [comment]
This looks good! It does seem this could break for people that have custom styling applied to their datepickers. I'd suggest we merge this as part of a major release that's coming up soon.

**Comment by ScottAgirs** [comment]
> This looks good! It does seem this could break for people that have custom styling applied to their datepickers. I'd suggest we merge this as part of a major release that's coming up soon.

Awesome! 🙌🏼 
Is there a rough timeline for the next Major release?

**Comment by martijnrusschen** [comment]
I'm prepping a major release for this week, and would like to get this one in. Can you take a look at the merge conflict so I can go ahead and merge this?

**Comment by ScottAgirs** [comment]
Hey @martijnrusschen that's awesome, wishing good luck and a smooth slide for the release! Conflict resolved! 🥂

**Comment by martijnrusschen** [comment]
Thanks!

**Comment by Sahil-177** [comment]
I'm trying to customize the color of the navigation icons (previous and next arrows) in the ReactDatePicker component. However, despite applying various CSS styles and Tailwind CSS utility classes, the color changes are not being reflected.


**If anyone can help with this issue or provide guidance on how to correctly apply these styles, it would be greatly appreciated.**

**Pull request merged**
