### PR TITLE
Ignoring yarn.lock

### PR DESCRIPTION
**Pull request by mberneti**

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you tell me why you want to ignore this?

**Comment by mberneti** [comment]
The problem is, once a developer run yarn install on its own computer and have the yarn.lock file pushed to git, all packages are resolved to "https://registry.yarnpkg.com/*" which is not accessible on out CI machine, so even when our CI machine has a yarn config set registry {out-local-registry}, yarn tries to fetch packages from registry.yarnpkg.com which causes network errors!

**Comment by alex-shamshurin** [comment]
The typical workflow is to INCLUDE `yarn.lock` everywhere into git. I'm not sure we should break it for this specific case.

**Comment by martijnrusschen** [comment]
Agree, it's best practice to have the yarn.lock file checked into git.

**Pull request closed without merging**
