### PR TITLE
Fix #4420: Update home key and end key navigation in Calendar component

### LINKED ISSUE #4420: Keyboard accessibility not aligned with ARIA authoring practices guide
**Describe the bug**
Some of the keyboard shortcuts are not aligned to what the W3C WAI-ARIA.
[Date Picker Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/)
Like the Home and End button should go to the first and last day of the week.

**To Reproduce**

1. Open the calendar
2. Press Home on keyboard
3. Previous year is selected

**Expected behavior**
Should move the selected day to the first day of the week.

### PR DESCRIPTION
**Pull request by balajis-qb**
Closes #4420

## Description
This PR addresses the navigation behavior in the calendar component to enhance accessibility based on W3C WAI-ARIA principles.  Previously, the home and end key handers navigated one year before and after the selected (which is the handlers for shift+PageUp and shift+PageDown), which could be confusing for users.  The update modifies the behavior to move to the first and last day of the week, providing a more intuitive and accessible experience.

[Reference Link](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/#:~:text=the%20previous%20day.-,Home,to%20the%20last%20day%20(e.g.%20Saturday)%20of%20the%20current%20week.,-Page%20Up)

## Changes Made
- Updated home and end key handlers in the calendar component.
- Navigation now focuses on the first and last day of the week, improving usability.
- Updated the corresponding test cases.

## Related issues
Closes #4420

I'll create a separate PR to fix the shift+pageUp and shift+pageDown issue, currently, it's working like PageUp and PageDown

### CODE REVIEW

**Comment by balajis-qb** [comment]
Currently, the test case of this branch is failing because of some existing issues in the test case in the main branch itself.  I'll analyze the issue and work on it.
image

**Comment by balajis-qb** [comment]
> This makes the appropriate change as described, but makes me wonder if there is any documentation that should also be updated to go along with it
> 
> Image of James D **James D**
> 
> Reviewed with ❤️ by [PullRequest](https://www.pullrequest.com)


Thank you for reviewing my PR.  Currently, I don't think we documented the keyboard navigation anywhere.  We just documented a way to [disable the keyboard navigation](https://reactdatepicker.com/#example-disable-keyboard-navigation).  I think as we are following the W3C WAI-ARIA principles we don't need to document it anywhere.

@martijnrusschen, Let me know if I need to update the current functionality anywhere.

**Comment by barettjfed** [comment]
@balajis-qb Thanks for doing this! Just FYI there is documentation in the read me about it. Wondering if that should get updated.
[Read me](https://github.com/Hacker0x01/react-datepicker?tab=readme-ov-file#keyboard-support)

**Comment by balajis-qb** [comment]
Thank you @barettjfed for letting me know, I'll update the file

**Pull request merged**
