### PR TITLE
added timeClassName prop

### PR DESCRIPTION
**Pull request by bresam**
added a prop named timeClassName which is an equivalent to dayClassName for times.
This allows to add classes to timeItems in dropdown-list 

Supported params are time, currH and currM: timeClassName(time, currH, currM)

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you add a test for this to make sure it works, and keeps working in the future?

**Comment by bresam** [comment]
Hi @martijnrusschen 

Thanks, i like to add these tests, but i am struggling with the environment, can you support?

while running "yarn i" i get this one:
> ERROR in ./docs-site/src/boot.jsx
Module parse failed: react-datepicker/docs-site/src/boot.jsx Unexpected token (5:16)
You may need an appropriate loader to handle this file type.

while running "yarn test" i get such one foreach Test:
>WARNING in ./test/year_dropdown_test.js
Module parse failed: react-datepicker/test/year_dropdown_test.js Unexpected token (18:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (18:6)

Shouldn't this environment work out-of-the-box?
Any ideas why this fails?

Best Samuel

**Comment by bresam** [comment]
Hi @martijnrusschen 

Could solve issues with test suite.
And added a test for custom time className.

Best Samuel

**Comment by bresam** [comment]
Ok i'm done. Is it okay so?

**Comment by bresam** [comment]
Hey @martijnrusschen 

sending you a kindly ping for merge.

Best Samuel

**Comment by bresam** [comment]
Hey @martijnrusschen 

Do you need more for merging my PR?

Best Sam

**Comment by bresam** [comment]
hi @martijnrusschen 

I have merged the actual master branch and fixed demo for that extension.
Checked the failing test, it's not related to the changes i've done.

Seems the actual master branch is failing on that.

Hope that gets merged into master.

Best Samuel

**Comment by bresam** [comment]
Still like to get merged.

**Comment by martijnrusschen** [comment]
Looks like the build is failing. Can you check what;s up?

**Comment by bresam** [comment]
> Looks like the build is failing. Can you check what;s up?

Hi,
Just did a merge with the actual master. Seems to work fine. right?

**Pull request merged**
