### PR TITLE
ClassNames for dayname, header

### PR DESCRIPTION
**Pull request by tujger**
daynameClassName, headerClassName

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you help me getting this branch up to date with the latest changes in Master? Once updated, I can merge this PR.

**Comment by tujger** [comment]
Has taken the last version from Hacker0x01; and checked the differences.

**Comment by tujger** [comment]
Hello,

I pulled the last version from the source#master, and checked the
differences. All my changes are in the pull request (monthClassName,
daynameClassName, headerClassName and so on). Sorry, i have no time to
write tests. You may reject my request, if it is necessary.

Thank you.

Edward.
Mail: tujger@gmail.com.
Phone: 703-409-2907 (after 5.30pm).

**Comment by martijnrusschen** [comment]
If you can add a view tests for your functionality you added, I'm happy to get this merged.

**Pull request closed without merging**
