### PR TITLE
Drastically decrease size of the bundles

### LINKED ISSUE #1606: date-fns gets bundled into builds (es and lib) - file size over 300kb
### Expected behavior
date-fns is imported in es/index.js

### Actual behavior
es/index.js is 300kb in size as it includes full date-fns

### Steps to reproduce

Same issue also exists in lib/index.js

### PR DESCRIPTION
**Pull request by igoradamenko**
Fixes #1606.

Before there were all packages of date-fns included into the bundles. 

Now I added a filter as @glebtv suggested (it doesn't look fine, I think, but it works), and whole packages of data-fns are marked as externals by rollup.

Also I noticed that lodash was imported fully because of 'isEmpty' script. I'm not sure that it is actually needed so I removed it.

And, last thing, I found out that prop types weren't removed during building. So I removed them.

Before:

```
./dist:
22K react-datepicker-cssmodules.css
20K react-datepicker-cssmodules.min.css
20K react-datepicker.css
172K react-datepicker.js
18K react-datepicker.min.css
172K react-datepicker.min.js

./es:
840K index.js

./lib:
841K index.js

```

Now:

```
./dist:
22K react-datepicker-cssmodules.css
20K react-datepicker-cssmodules.min.css
20K react-datepicker.css
55K react-datepicker.js
18K react-datepicker.min.css
55K react-datepicker.min.js

./es:
101K index.js

./lib:
102K index.js
```

Anyway, I tested it in my project and it works fine.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Does this change anything in the way people install the package? Do we need to update the readme?

**Comment by igoradamenko** [comment]
I don't think so. Now all dist files import date-fns as they do e.g. for react. I just removed inlining of date-fns there.

Anyway, I think it's better to move date-fns to peer deps and write about it in the readme. Because now react-datepicker installs it's own date-fns version, and I think that it's better to ask users to install it by themselves.

**Comment by mvirbicianskas** [comment]
hey, quick question is this published in 2.4.0 or will it be published in later versions?

**Comment by agoldis** [comment]
@martijnrusschen, sorry to annoy, echoing @mvirbicianskas  👆🏻 - this is highly desired release.

**Comment by agoldis** [comment]
https://github.com/Hacker0x01/react-datepicker/releases/tag/v2.5.0 🎉

**Pull request merged**
