### PR TITLE
First attempt at ability to clear date inputs.

### PR DESCRIPTION
**Pull request by ryan1234**
There might be a way to do this already without this pull request, but I couldn't figure it out. =(

I have a form with date fields and each date field is nullable. This means the value can either be a valid date (datepicker handles this great), or it can be empty, which means `null` right now.

This PR is one approach to supporting the ability to "clear" a date value if the input text is empty. 

I realize `null` might not be the best thing to emit to onChange. Open to any ideas like an empty string etc.

Hoping this PR can be a first step towards a good solution.

### CODE REVIEW

**Comment by RSO** [comment]
Interesting approach. I get your hesitation concerning `onChange(null)` it doesn't seem optimal. I will see if I can dig into this PR a little further early this week. Thanks for taking the time to submit this suggestion, I really appreciate it!

**Comment by ryan1234** [comment]
Yeah I was thinking we could push out the function to clear to the user as an option prop, but I didn't want to clutter the "interface" to the component. Thanks for the review. =)

**Comment by ryan1234** [comment]
Just checking in to see if you've had a chance to think more about this PR.

**Comment by RSO** [comment]
Sorry for the wait. I didn't find the time to check this out any further, so lets just go with this solution!

**Comment by QingkaiLi** [comment]
Hi RSO, when will you do release? i'm waitting for the latest code

**Comment by martijnrusschen** [comment]
@QingkaiLi I'll make sure this will be released today!

**Comment by QingkaiLi** [comment]
Cool, then i needn't override it in my local. just waiting your new release. Thanks

**Comment by martijnrusschen** [comment]
Here it is: https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.7.0

**Comment by QingkaiLi** [comment]
I Checked out the new version but there is a issue: Uncaught TypeError: n.findDOMNode is not a function

**Comment by ryan1234** [comment]
What version of react are you using?

**Comment by QingkaiLi** [comment]
React 0.12

**Comment by QingkaiLi** [comment]
can you try : this.getDOMNode()

**Comment by QingkaiLi** [comment]
The issue occurs from  toggleFocus method in date_input.jsx. maybe  this.getDOMNode() works. can you fix?

**Comment by martijnrusschen** [comment]
Can you try upgrading to React 0.13? getDOMNode is being deprecated in favor of findDOMNode.

**Comment by martijnrusschen** [comment]
From the React 0.13 release notes:

> Added new top-level API React.findDOMNode(component), which should be used in place of component.getDOMNode(). The base class for ES6-based components will not have getDOMNode. This change will enable some more patterns moving forward.

https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html

**Comment by QingkaiLi** [comment]
i'm using React 0.12 and cause of too may depencies i cannot upgrade it. since react-datepicker is using React 0.12 can you just stay using the version and find other way to solve this problem?

**Comment by QingkaiLi** [comment]
Or can you release  react-datepick 0.6.1 using this.refs.input/this.getDOMNode() and React 0.12 and realse react-datepicker 0.7 using React0.13?

**Comment by QingkaiLi** [comment]
Because React 0.12 and 0.13 has huge differences. so can you do two release so that all of us can use your component no matter which React version we're using. Thanks

**Comment by RSO** [comment]
Hi @QingkaiLi I'm sorry that we weren't clearer on dropping support for React 0.12. If you provide a PR for an older version I might consider merging it, but I will not spend time myself on supporting older versions of React. 

Because of React's alfa-stage every new version will have breaking changes, which makes it harder to support multiple versions.

**Comment by SinisterGlitch** [comment]
Everything still works if you just uncomment this code.
	
  toggleFocus: function toggleFocus(focus) {
	    if (focus) {
	      //    React.findDOMNode(this.refs.input).focus();
	    } else {
	      //  React.findDOMNode(this.refs.input).blur();
	    }
  },

**Pull request merged**
