### PR TITLE
don't expose tether anymore

### PR DESCRIPTION
**Pull request by martijnrusschen**
Ref #329

### CODE REVIEW

**Comment by rafeememon** [comment]
@raptoria, is there a chance you could try this out before we merge it so we can make sure it solves your problem?  I built the branch and pasted the contents of react-datepicker.min.js here: http://hastebin.com/falidujulo.js  If you replace the contents of react-datepicker.min.js with that you should be able to try it out.  Let us know!

**Comment by raptoria** [comment]
It solves the setState error, and works wonderfully in IE10 as well.

**Comment by rafeememon** [comment]
Ah yeah, I think `datepicker__container` got changed to `datepicker__tether-element`.  Here's the new stylesheet: http://hastebin.com/cuheroyema.css  Let us know if that works.

**Comment by raptoria** [comment]
are you guys going to publish the latest version to NPM? thanx!

**Comment by martijnrusschen** [comment]
Just released v0.21

**Pull request merged**
