### PR TITLE
Fix top popup position issue

### PR DESCRIPTION
**Pull request by alextkachuk**
Remove filter isWeekInMonth in month.jsx for showing the same calendar size (6 rows) in different months. It is usual approach for date picker that it has the same size calendar. In this case, there is not the issue like #361 and size is predictable for users. 

Connect to #361

### CODE REVIEW

**Comment by benwill** [comment]
+1, think this is much better than how it currently works

**Comment by rafeememon** [comment]
Hey @alextkachuk, thanks for the PR.  This is a pretty large departure from the current functionality and we need to be very careful when making this change.  I'm not sure that the argument that this is the usual approach is correct; some take our approach (e.g. [jQuery UI datepicker](https://jqueryui.com/datepicker/)) and others take the other (e.g. [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/)).  I think at the very least that this should be behind a boolean flag option, and we most certainly need an answer for #296/#417 as well.  Let me know what you think.

**Comment by rafeememon** [comment]
The popover position issue can almost certainly be directly fixed as well -- at a high level what probably needs to happen is that the calendar should be repositioned when the month changes

**Comment by alextkachuk** [comment]
@rafeememon In my view, the best quick solution is setting opacity: 0.x (for example) for days are not in the current month and add my changes (fixed calendar).

Option for fixed or not is not good approach because in this case - not fixed mode will have a strong bug. For example, now I can't use react-datepicker in my current project because some modal window needs only top-view calendar and this bug my users found in production.

On the other hand, if popover position will fix in short period it would be great and in this case option for fixed/not fixed would be additional sugar :-)

**Comment by rafeememon** [comment]
> In my view, the best quick solution is setting opacity: 0.x (for example) for days are not in the current month and add my changes (fixed calendar).

Potentially; this was once the behavior but it was changed because the dates looked too similar to disabled dates.  See the other issues I mentioned for more discussion about that

> Option for fixed or not is not good approach because in this case - not fixed mode will have a strong bug. For example, now I can't use react-datepicker in my current project because some modal window needs only top-view calendar and this bug my users found in production.

Yes, but the not-fixed mode is the current behavior, so it would be no worse than it is now.  Adding the extra rows without an option to turn them off is potentially undesired behavior for many consumers, including myself.

> On the other hand, if popover position will fix in short period it would be great and in this case option for fixed/not fixed would be additional sugar :-)

I definitely think that the ideal outcome here is that the position problem is solved, which would probably make this PR a moot point.  I'm not comfortable merging this yet because of the things we've been talking about, but feel free to take a stab at the position problem, maybe with the approach I mentioned before.

**Comment by alextkachuk** [comment]
@rafeememon It makes sense, but now react-datepicker has the serious bug. The solution needs to change the tether library - it could be a long process. Can I add the option "isCalendarFixed" (or give me another name) and implement this optional logic? I think, anyway this option would be useful.

**Pull request closed without merging**
