### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by honzajerabek**
update css files dist paths for 0.60.0

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Hmm, I would prefer changing back the compiled CSS files to the original names to avoid breaking behaviour for existing installations.

**Comment by honzajerabek** [comment]
Agree! I saw you were doing some building refactors, so I changed the names, but previous state would be better for most users.. I can send a PR after lunch ^^

**Comment by martijnrusschen** [comment]
Thanks, yes that would be appreciated!

**Comment by honzajerabek** [comment]
pushed a new PR, closing this one

**Pull request closed without merging**
