### PR TITLE
Added setOpen as prop to week select function

### PR DESCRIPTION
**Pull request by charliearlie**
Currently the calendar never closes if the user selects a week number and that is due to the week select logic happening in it's own component. This component needed access to the setOpen function to close.

### CODE REVIEW

**Comment by charliearlie** [comment]
I have tested each and every outcome of my changes and it says the new test coverage only covers 80%?

**Comment by martijnrusschen** [comment]
Don't worry too much about it, if you can fix the merge conflicts I can get it fixed.

**Comment by charliearlie** [comment]
Merge conflicts again. Is this going to be merged, or should i just close it?

**Comment by martijnrusschen** [comment]
Sorry, I can merge it directly after you resolved it. Didn't catch this one earlier.

**Comment by charliearlie** [comment]
Thanks. I've resolved the conflicts.

**Comment by charliearlie** [comment]
CodeCov says 100% of diff covered now too. Weird...

**Comment by martijnrusschen** [comment]
Thanks, codecov is a strange tool.

**Pull request merged**
