### PR TITLE
Adding showPreviousMonths property

### PR DESCRIPTION
**Pull request by gyugyu**
This pull request adds `showPreviousMonths` property to show previous months when monthsShown is configured.

### CODE REVIEW

**Comment by kblodget** [comment]
Can this functionality be added to the master branch?

**Comment by kblodget** [comment]
Can this PR be added to the master branch?

**Comment by martijnrusschen** [comment]
Got some merge conflicts, but should be good to go when resolved.

**Comment by kblodget** [comment]
Is there any way this may be added soon.

**Comment by martijnrusschen** [comment]
@kblodget We're waiting on resolving the merge conflicts.

**Comment by martijnrusschen** [comment]
Closing due inactivity.

**Pull request closed without merging**
