### PR TITLE
Fixed month aria-label date format (Fixes: #1767)

### PR DESCRIPTION
**Pull request by csilkwor**
Fixes issue #1767

### CODE REVIEW

**Comment by negativetwelve** [comment]
Is this going to come out in a patch release soon? This issue is breaking our site atm 😞

**Comment by Fluorz** [comment]
+1

**Comment by maverickdude** [comment]
This error was blowing my mind. Good to see that it's fixed now. Wonder when this will release.

**Comment by martijnrusschen** [comment]
Released earlier today

**Pull request merged**
