### PR TITLE
Fix class not applied on day component for datepicker with `selectsRange` prop

### PR DESCRIPTION
**Pull request by c-falardeau**
- Apply the `react-datepicker__day--selecting-range-end` class on the day component while user is selecting the end date for the range
- Added unit test

I observed that for datepicker having the `selectsRange` prop, when the user is selecting a range only the `react-datepicker__day--selecting-range-start` is set on the day component starting the range. While the user is moving the mouse on other day components, the class `react-datepicker__day--selecting-range-end` would not be applied on the hovered day to indicate that he is selecting that day as the end date.

I would need this class to be applied to perform custom styling for achieving this kind of styling:

chrome_z0vE4vZ9OU

This would help me to not continue the blue line after the end date.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Merging in the latest master branch should fix the CI checks on the Pull request.

**Comment by c-falardeau** [comment]
Good catch thanks :)

**Comment by c-falardeau** [comment]
Hello, do you know when the new release will be available containing this PR please?

Best regards,
Christian

**Comment by c-falardeau** [comment]
Thanks :)

**Comment by c-falardeau** [comment]
Hello @martijnrusschen, I was wondering if it is possible to get a new release including this fix please :)

**Comment by cnorthfield** [comment]
@martijnrusschen any chance of a release of this, please?

**Comment by jgregory-apogee** [comment]
For now I'm working around this with `.react-datepicker__day--in-selecting-range:hover`.

**Pull request merged**
