### PR TITLE
Add prop to enable adding custom classes to days based on days date

### PR DESCRIPTION
**Pull request by martinek**
This adds `dayClassName` prop. This can be set to function which gets called for each day of rendered calendar. Function can return any object supported by classnames utility and it will be added to classnames of that day. Function gets rendered day's date as an argument.

This for example enables completely custom highlighting without the need to specify highlighted days upfront.

If function returns undefined, no class is added.

### CODE REVIEW

**Comment by utsavdevsharma** [comment]
This is exactly what we need in advanced usage. I would like to request, it will be really helpful if we can merge #835 soon.

**Comment by aij** [comment]
@martinek Please avoid committing changes to build outputs like docs-site/bundle.js. It creates needless conflicts.

Other than that, this looks good.

**Comment by utsavdevsharma** [comment]
Big Thanks ! 👍 💯

**Comment by Rachomir** [comment]
@martinek example in docs is not very clear for myself is there any chance you can explain to me how for example you would give a class depending on previous button click. 

Let say you have three buttons "red" "green" and "blue" and depending on chosen button you would give className to a perticular day - .react-datepicker__day-green or .react-datepicker__day-red or .react-datepicker__day-blue. Everytime you click on a different day you have an option to click a button which change color of that day in datepicker.

Thanks in advance

**Comment by martinek** [comment]
Well, you would have to somehow build up and object where you would store which day is which color. Then you would use something like
```
dayClassName={date => dayColors[date]}
```

In dayColors you would have something along

```
dayColors = {
    '09-10-2017': 'red',
    '10-10-2017': 'blue'
}
```

or something like that

**Comment by Rachomir** [comment]
@martinek first of all thanks for your help.

I tried to do it like you said unfortunately without success. Any other ideas? I thought maybe date format should be different but I tried many things and still doesn't work.

**Comment by martinek** [comment]
Here is a working example that should help you out:
https://codesandbox.io/s/825l6m0zr2?module=%2FExample.js

**Comment by Rachomir** [comment]
@martinek thanks a lot for your patience and apologies for beeing pain in the ass :)
Do you think it is possible to keep those "coloured dates" in database and render datepicker with days already coloured (accordingly to data fetched from db)? plus add new on click, like you did with state?

**Comment by Rachomir** [comment]
I think I know how to do it. I will keep the data in db than on componentWillReceiveProps I will setState with date + colour. Em I right?

**Comment by Rachomir** [comment]
My concern is also this bit 

`<style dangerouslySetInnerHTML={{__html: `
          .red { color: red }
          .green { color: green }
          .blue { color: blue }
        `}} />` 

How would I use it if I fetch data from DB? instead of clicking

**Comment by Rachomir** [comment]
@martinek would you be able to help me?

**Comment by martinek** [comment]
The example linked intended to show you how the prop on DatePicker works. I'm positive you can keep the data from state in database. I don't know what you mean with new click.

Also if you are designing you own application, you don't need `<style dangerouslySetInnerHTML...>`. That was something i used just for the example.

I'm not sure what you expect of me? You are apparently creating some project and without whole picture it is hard to recommend any solution. Also it is kind of out of scope for pull request discussion.

You might get more info on stackoverflow.

**Pull request merged**
