### PR TITLE
add month dropdowns

### PR DESCRIPTION
**Pull request by jochenberger**
The styles are horribly broken, but apart from that, it works.
Oh, and it has no tests...

### CODE REVIEW

**Comment by jochenberger** [comment]
It probably makes sense to review #646 first and revisit this afterwards.

**Comment by jochenberger** [comment]
@martijnrusschen this should be ready for review

**Comment by martijnrusschen** [comment]
Would you mind adding an example to the docs on how this works? Similar to the year dropdown.

**Comment by jochenberger** [comment]
Done. But I noticed that the year is not dsplayed in the header if `showMonthDropdown ` is set. This is probably a bug. Might be related to #533.

**Comment by martijnrusschen** [comment]
Awesome, thanks for the help!

**Pull request merged**
