### PR TITLE
add openToDate prop

### PR DESCRIPTION
**Pull request by lbntly**
Resolves issue https://github.com/Hacker0x01/react-datepicker/issues/320. 

Allows you to specify a date at which to open the date picker initially (without setting a selected value).

### CODE REVIEW

**Comment by rafeememon** [comment]
Hey @lbntly, thanks for the contribution, this looks good!  Could you remove the compiled docs files (bundle.js and style.css) from the PR -- we automatically generate those when we make a release.  Other than that, this should be good to go.

**Comment by lbntly** [comment]
@rafeememon Oh right, my bad! I've gone ahead and removed those changes, would you prefer I rebase/squash those commits before merging or leave as is?

**Comment by martijnrusschen** [comment]
Nice work!

**Comment by rafeememon** [comment]
Thanks @lbntly!  We can squash on merge so leaving it as-is is fine

**Pull request merged**
