### PR TITLE
Remove usages of react-onclickoutside to support React 19

### PR DESCRIPTION
**Pull request by hamidrezahanafi**
## Description
Closes https://github.com/Hacker0x01/react-datepicker/issues/4801
Closes https://github.com/Hacker0x01/react-datepicker/issues/4605

**Problem**
React 19 removed `findDOMNode` and `react-onclickoutside` is not supported

**Changes**

- Remove `react-onclickoutside` and replace with custom wrapper
- Update the `onClickOutside` to use `MouseEvent` instead of `React.MouseEvent` since it's a document event listener

## Contribution checklist
- [x] I have followed the [contributing guidelines](https://github.com/Hacker0x01/react-datepicker/blob/main/CONTRIBUTING.md).
- [x] I have added sufficient test coverage for my changes.
- [x] I have formatted my code with Prettier and checked for linting issues with ESLint for code readability.

### CODE REVIEW

**Comment by hamidrezahanafi** [comment]
> The change looks good to me. On the other hand, the discussion on #4605 mentioned using `floating-ui` instead, https://floating-ui.com/docs/usedismiss. Any specific reason to build the custom solution instead of using that?
> 
> Image of Xiaoyong W **Xiaoyong W**
> 
> Reviewed with ❤️ by [PullRequest](https://www.pullrequest.com)

Not all usages of the `react-onclickoutside` could be replaced by `useDismiss` like month and year dropdown which are not using `useFloating`. I figured we probably don't want to have two different things to manage outside click.

**Comment by martijnrusschen** [comment]
Thanks! I'll do some manual testing before merging. Stay tuned.

**Comment by martijnrusschen** [comment]
This seems to work fine, I'm going to merge this.

**Comment by hamidrezahanafi** [comment]
@martijnrusschen Is there any plan to cut a new release soon? React 19 is on the horizon and I would like to start some testing with this change.
Thank you!

**Pull request merged**
