### PR TITLE
Fix #4268: Retain the selected date when changing the time

### LINKED ISSUE #4268: Changing time is resetting date to current date
**Describe the bug**
When we manually change the time value, the date value is reset to the current date.

**To Reproduce**
1. Considering current date is `sept 20th`
2. Pick `sept 21th` in the calendar picker
3. Modify the time in the time picker
4. The date is reset to `sept 20th`

**Expected behavior**
Changing the time in the time picker should not alter the selected date

**Additional context**
Bug seems to have appeared with the release of version 4.18.0.
Had to lock the version to 4.17.0 to fix the problem.

### PR DESCRIPTION
**Pull request by balajis-qb**
Closes #4268

### Summary
This PR addresses an issue where the component was resetting the selected date of the component to the current date when changing the time. The fix ensures that the selected date remains unchanged when modifying the time, enhancing the user experience.

### Changes Made

- Implemented logic to preserve the selected date when updating the time.
- Refactored the onTimeChange function to check if the prop date is null before using the current date

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you add a test to ensure the fix keeps working?

**Review by martijnrusschen — CHANGES_REQUESTED** [review]
This change looks good, but please add a test to avoid breaking this in the future.

**Comment by balajis-qb** [comment]
Thank you for your feedback, team.  I'll add the testcases and update the PR

**Comment by martijnrusschen** [comment]
Thanks for adding the tests, please ensure the CI job is succeeding so we can get it merged.

**Comment by balajis-qb** [comment]
Hi @martijnrusschen , 

The test case failed due to an existing issue there in the datepicket_test.test.js file.  Please check the issue I created for more details https://github.com/Hacker0x01/react-datepicker/issues/4283

I fixed the issue and updated this PR.  Kindly review and let me know if any changes required

**Review by martijnrusschen — APPROVED** [review]
Thanks for the extra effort to make the tests work.

**Pull request merged**
