### PR TITLE
Remove wrong react dependency to fix documentation

### PR DESCRIPTION
**Pull request by martijnrusschen**
Fixes https://github.com/Hacker0x01/react-datepicker/issues/2647

Change introduced in https://github.com/Hacker0x01/react-datepicker/pull/2626, but seems to break the documentation site. Reverting change to make the docs site work again.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
This fixes the docs site, but breaks the test suite. Looking for a better solution.

**Comment by czabaj** [comment]
I mentioned the problem in [a comment here](https://github.com/Hacker0x01/react-datepicker/pull/2626#issue-548299565).

The problem was always present but reveals after the upgrade of react-popper, for it uses React hooks under the hoods which relies strictly on a single React instance.

This shall cause no problem in production, for devDependencies are not installed there, but breaks the app for local development.

The best solution is to separate tests into their own directory with their own peer dependencies.

See the linked comment for more info. Also, be aware that the upgrade of react-popper shall be a breaking change of react-datepicker, for propTypes is changed backward incompatibly and the positioning via `offset` modifier might break some customers logic.

**Comment by martijnrusschen** [comment]
@czabaj You're right, I overlooked the comment and didn't take the consequences into account. It's currently breaking our reactdatepicker.com site which is used for public documentation and examples. 

I'm going to be reverting the PR to mitigate the broken docs site for now, but I do agree we need to look into moving the tests out to get rid of the double React dependency. Once this is fixed, I'll release the upgrade again in a major version upgrade as the breaking change shouldn't happen in a minor upgrade.

**Comment by martijnrusschen** [comment]
Closing this PR as this isn't the right approach.

**Comment by czabaj** [comment]
@martijnrusschen hey 👋 

should I re-open the pooper upgrade and draft a solution with the test folder?

**Pull request closed without merging**
