### PR TITLE
Inline calendar

### PR DESCRIPTION
**Pull request by kvasa**
Hi,

I needed inline version of calendar for my project (calendar rendered directly without TetherComponent), so I added new prop `inline` to achieve this behavior for the user and implemented this functionality. I also added new example with `inline` prop.

I can use my enhanced component directly, but maybe you will find this feature useful for other people and you will merge it directly into your code.

Thank You very much for awesome date picker!
Michal

### CODE REVIEW

**Comment by martijnrusschen** [comment]
I like the idea. Can we get some test coverage for this?

**Comment by kvasa** [comment]
Sure, I will add some tomorrow.

**Comment by kvasa** [comment]
So I added 3 simple tests mainly to check if TetherComponent is rendered or not. Is it ok like this or should I add some more?

**Comment by rafeememon** [comment]
Hey @kvasa, thanks for the contribution, this looks good.  I'll wait for the final approval from @martijnrusschen before we merge this in.

For SA: I think the way we'll want to handle this in v1.0 is to remove the `inline` prop and instead allow direct consumption of the `Calendar` component.  However this is a good stopgap solution until we get to that world.

**Pull request merged**
