### PR TITLE
Add support for name attribute on input element

### PR DESCRIPTION
**Pull request by kevzettler**

### CODE REVIEW

**Comment by kevzettler** [comment]
@martijnrusschen any thoughts on this? I noticed its basically the same as #108 after I opened. Definitely a needed feature and small commit.

**Comment by kevzettler** [comment]
ping @RSO

**Comment by martijnrusschen** [comment]
Sorry for the delay @kevzettler. I'm really busy this week, so I'll try to get back to you this weekend or early next week! One thing I noticed is that your PR changes 20.000 lines of code, this makes things really hard to review. Is there any way to get your change smaller?

**Comment by kevzettler** [comment]
@martijnrusschen the 20,000 lines are from running and committing the built assets from `grunt`. I thought that was part of the contribution process would you rather those not be commited?

**Comment by kevzettler** [comment]
ok @martijnrusschen I've removed the built files and now this PR is almost exactly the same as #108 so either one would work for my needs

**Comment by martijnrusschen** [comment]
I merged #108 yesterday and will release a new version before the end of this week.

**Comment by kevzettler** [comment]
ok nice closing this then

**Pull request closed without merging**
