### PR TITLE
Rename getInitialState

### LINKED ISSUE #832: Getting warning on render
When the library is rendered I'm getting:

`Warning: getInitialState was defined on t, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?`

### PR DESCRIPTION
**Pull request by mgrdevport**
fix #832 
Rename getInitialState function to calcInitialState.

### CODE REVIEW

**Comment by ilyagelman** [comment]
+1 for this

**Comment by martinliptak** [comment]
+1

**Comment by jmas** [comment]
+1 it will be great to see that fix in master, we can't pass QA's without it. 😄

**Comment by martijnrusschen** [comment]
@mgrdevport I tried merging with master to get the latest changes in. Can you verify this is done correct? I want to make sure I didn't merge in any unwanted changes.

**Comment by dmitryk-dk** [comment]
+1

**Comment by Ifgen09** [comment]
+1

**Comment by mgrdevport** [comment]
@martijnrusschen See my latest commit, I've upgraded sinon and enzyme to the latest version to be compatible to the newer react 15.5 version. I think it's fine now.

**Comment by dmitryk-dk** [comment]
@martijnrusschen can you update the status of this fix, because we have the error in console so this is not good for users.

**Pull request merged**
