### PR TITLE
fix(minDate,maxDate): Fixing minDate/maxDate to allow one or the other

### PR DESCRIPTION
**Pull request by jgodi**
Fix: Allow the user to specify `minDate` or `maxDate`. 
Use Case: A user wants to allow the input of dates before or after a specific date and not just in-between two dates

If the user specifies `minDate` only then it will make sure the date `isAfter`. 
If the user specifies `maxDate` only then it will make sure the date `isBefore`.
If the user specifies `minDate` and `maxDate` it will make sure the date is within the range.

XR7vBGiFKa

### CODE REVIEW

**Comment by jgodi** [comment]
Any update on this one? Anything that you would like me to address or fix?

**Comment by martijnrusschen** [comment]
Looks good, can you fix the merge conflicts so we can merge this?

**Comment by martijnrusschen** [comment]
Or just remove the changes to:
docs-site/bundle.js
docs-site/style.css

**Comment by jgodi** [comment]
On it, thanks!

**Comment by jgodi** [comment]
@martijnrusschen Done!

**Pull request merged**
