### PR TITLE
Add option for month/year drop-down and week peek

### PR DESCRIPTION
**Pull request by iknowcss**
This addresses #462 and adds an additional feature to "peek" at the first full week in the next month.

API to use `<select>` dropdowns is:

```
<DatePicker
    {...}
    dropdownMode="select" 
    showYearDropdown 
    showMonthDropdown />
```

API "peek" into next month is

```
<DatePicker
    {...}
    peekNextMonth />
```

Changes include:

* Add year and month `<select>` dropdowns
* Workaround: Cancel date input focus if focusing on year/month `<select>`
* Create base CSS for year and month dropdowns
* Add option to "peek" into the next month's first full week
* Refactor week rendering logic
* Update README and examples
* Bugfix: Make min/max date apply to YearDropdown
* Bugfix: Fix moment.js deprication warnings

I'm happy to adjust the API if you're not happy with it. I've tried to be as consistent as I can with testing. There are some `// TODO`s where there might be a non-`<select>` month picker.

Please let me know what you think!

Cheers,
Cody

### CODE REVIEW

**Comment by iknowcss** [comment]
Travis is failing but I don't understand why? I can't get the tests to fail for me locally.

**Comment by martijnrusschen** [comment]
Looking into the same issue for Master. I'll keep you posted.

**Comment by martijnrusschen** [comment]
@iknowcss I made the test pending to fix the build. Couldn't find the root cause of the issue and wasn't able to reproduce this locally. Go ahead and rebase with master to fix your PR.

**Comment by iknowcss** [comment]
@martijnrusschen I just realized I have caused a regression in `fixedHeight` during my refactor. It is late now so I will fix tomorrow.

**Comment by iknowcss** [comment]
@martijnrusschen I have completed my changes and added new tests to prevent a regression of `fixedHeight` again. When you have a chance, would you please have a look at the code and let me know if you have any questions?

Cheers!
Cody

**Comment by iknowcss** [comment]
Thanks Martijn!

**Comment by sanheng** [comment]
i can't use it through npm install react-datepicker@0.29.0 --save
and i tried dropdownMode="select" is not working

**Comment by iknowcss** [comment]
Hey sanheng, the changes have been merged to master but they have not been published to npm yet. They should be available in version 0.30.0.

**Pull request merged**
