### PR TITLE
Remove second autoFocus example

### LINKED ISSUE #1212: Flickering issue when focusing on input at the top of the docs site
### Expected behavior
Component becomes focused and accepts input

### Actual behavior
Screen flickers and scroll position changes rapidly. See video.

datepicker-bug

### Steps to reproduce
Load demo page https://reactdatepicker.com/ in Chrome (Tested on OSX Chrome 63.0.3239.132)
Before scrolling or clicking anywhere, click inside the input at the top of the page

Issue also exists on Safari

### PR DESCRIPTION
**Pull request by aij**
hero_example already has autoFocus, and having two inputs
focused by default dosn't make sense.

Fixes #1212 #1334

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you check the failing build?

**Comment by aij** [comment]
I'm seeing the same test failures on master and v1.5.0, but I see they passed on v1.5.0 before. Any idea what may have changed?

Anyway, I'll look into it...

**Comment by aij** [comment]
Oh, it's another transient failure. :disappointed: 

What changed is today's date, so today is now rendered on both the last week of May and the first week of June (before the 1st). I expect it will start passing again next week, but it would be good to make the test more reliable.

**Comment by aij** [comment]
I think 639fddd4aaa0def6a44995f29e82ffacd51cf430 could be reverted now. It was just to scroll back to the top after auto focusing the bottom example, wasn't it?

**Pull request merged**
