### PR TITLE
Solution to issue #1337

### PR DESCRIPTION
**Pull request by CalebKAston**
Added a prop and logic for keeping the currently displayed months the same when working with a multi-month inline calendar.

See issue: [https://github.com/Hacker0x01/react-datepicker/issues/1337](https://github.com/Hacker0x01/react-datepicker/issues/1337).

This specifically applies to multi-month inline datepickers. Originally, when a date was selected in a month other than the first month, when the months were re-rendered, the calendar "jumped" to make the selected month the first month rendered. I added logic that keeps track of which rendered month the date was selected in and then the code uses that month to render the months in the same order they were prior to a date being selected. This stops the "jumping" that was happening.

This new functionality is the default behavior. Though, should someone desire that the jumping be maintained, everything I added can be negated by setting the new prop `inlineFocusSelectedMonth` to `true`.

I did do thorough QA with these changes throughout all of the examples and it appears that I was successful in only altering what I intended to alter.

Specific changes:
- Added a prop to toggle the new functionality (defaults to using the new functionality)
- Added internal logic to track which month the date was selected in when using an inline datepicker
- Used that additional information when rendering months to stop the "jumping" from happening

### CODE REVIEW

**Comment by booyokkk** [comment]
@CalebKAston I like your solution for #1337, but I think you should add some tests for that. If you have trouble with that, please, ping me and I'll help you.

**Comment by CalebKAston** [comment]
@booyokkk I have added a new commit to this branch which proves the functionality through several new tests. Let me know if there is anything else you would like me to do.

**Comment by booyokkk** [comment]
@CalebKAston Please pull the latest master to your branch and resolve conflicts

**Comment by booyokkk** [comment]
Great job @CalebKAston. @martijnrusschen What are you think about this solution?

**Comment by CalebKAston** [comment]
@booyokkk @martijnrusschen Any news on this solution being merged into the project?

**Comment by CalebKAston** [comment]
I updated PR to resolve the conflicts. The build is failing because another test (completely unrelated to the work I was doing) is now failing.

**Comment by shettyashwitha** [comment]
When will this be merged? Can someone update the status on this, please?

**Comment by martijnrusschen** [comment]
Looks like the CI is failing. I can't merge a failing PR.

**Comment by CalebKAston** [comment]
@martijnrusschen I resolved the issue with the CI failing. Can we get this merged now?

**Comment by shettyashwitha** [comment]
@martijnrusschen I have a dependency on this. Can you please merge this PR?

**Comment by fooberichu150** [comment]
Is this merge going to happen anytime soon?

**Comment by shettyashwitha** [comment]
> Is this merge going to happen anytime soon?

+1

**Comment by martijnrusschen** [comment]
Sorry took a bit longer than usual. Thanks for your contribution!

**Comment by etorreswitbooking** [comment]
Hi, I have a trouble. When I add the `inline` prop, my datepicker functionality changed a lot. Can you put this `inlineFocusSelectedMonth` without inline property?

**Pull request merged**
