### PR TITLE
Fix window undefined issue

### PR DESCRIPTION
**Pull request by CalebKAston**
These changes should prevent the package from crashing sites during Server Side Rendering and other scenarios in which `window` is undefined.

I tried to come up with a way to test the functionality here but I can find no possible way to run a test in your test structure to run a test in which window is undefined. Window is unchangeable.

Addresses Issues: #1619 and #1633.

### CODE REVIEW

**Comment by brenoasm** [comment]
Someone could review and/or approve this?

**Comment by martijnrusschen** [comment]
Thanks!

**Comment by The-Code-Monkey** [comment]
can we rebuild the version on npm as this hasn't been pushed to there as far as i can see.

**Comment by suprraz** [comment]
+1 for npm push

**Pull request merged**
