### PR TITLE
Changes to support disabling auto correction of dates

### PR DESCRIPTION
**Pull request by greg-a-smith**
These are the suggested changes to address issue #768 .

### CODE REVIEW

**Comment by greg-a-smith** [comment]
Looking at the code coverage report, it doesn't appear there are any additional new lines that can be tested.  There are some additional lines defining the prop and its default values which seem to be causing the overall line coverage percentage to drop.  I am not quite sure how to address this.

Please let me know how to proceed.  Thanks!

**Comment by osbornm** [comment]
@martijnrusschen Any idea on the Code Coverage issue @greg-a-smith is talking about? And is there anything else needed for this PR?

**Comment by martijnrusschen** [comment]
The coverage reports aren't always helpful. I'm fine with merging in this case.

**Comment by Trend20** [comment]
Is there any solution for this when using an Angular Datepicker? I have got the same problem but I am using Angular.

**Pull request merged**
