### PR TITLE
Support dynamic props + add an onBlur callback when calendar is closed.

### PR DESCRIPTION
**Pull request by at0g**
- Updated babel / jsxhint to support esnext for rest/spread operator
- Added blur/change example to examples app
- Added onChange as required prop (An error is triggered if it's not set)

### CODE REVIEW

**Comment by at0g** [comment]
Sorry, not sure how to fix the jest tests to use babel {stage: 0}.

Also, not too sure what happened to example/example.js - all the quotes changed from double to single when built on my machine.

**Comment by martijnrusschen** [comment]
Hi @at0g 

Thanks for taking the time to create this PR. I'm really busy at the moment, but I'll try to take another look this week to find out what's going wrong.

**Comment by RSO** [comment]
Hi @at0g! Thanks for taking the time to setup this PR. Unfortunately I was away on vacation, so it took me a little longer to respond. From the looks of it you're doing a couple of different things, that might make it harder for me to review this PR (and see what goes wrong), therefor I'll try and get some of the (needed) changes in master separately.

I will start with enabling ES6 and upgrading `babel-loader`, and adding `onChange` as a required prop.

After that I'll check back on this diff, I'm not entirely sure on the use of the spread operator now, but I'll hope to get things running first, so I can see how everything plays out.

**Comment by RSO** [comment]
Upgraded `babel-loader` and `propTypes` are now in master. I think that it might be wise to leave the spread operator as is for now, and just focus on the `onBlur` functionality, which is interesting on its own. Do you think that you'll have time to update your PR?

**Comment by at0g** [comment]
Thanks @RSO - I'm using my fork on a project, so can't make breaking changes to it. However, I can send you a new PR (from a branch) with just the blur callback.

**Comment by RSO** [comment]
That would be great, thanks!

**Comment by at0g** [comment]
Hey @RSO - new PR #129 contains just the onBlur callback. Going to close this PR.
Thanks.

**Pull request closed without merging**
