### PR TITLE
CDN support added to the README

### PR DESCRIPTION
**Pull request by ehkasper**
Hey guys, I have added the CDN support to the readme file, describing the links of minified files. Hope it helps. See issue #501.

### CODE REVIEW

**Comment by ehkasper** [comment]
Hey folks! Im pretty sure there was a discussion here lol 

Have you removed last comments?

**Comment by martijnrusschen** [comment]
Haha no, it's in #501

**Comment by ehkasper** [comment]
oh, shit. Sorry :shipit:

**Comment by ehkasper** [comment]
Hey, please have a look at the updated message. I think it's pretty simple, just to let people know they can link this project's resources w/o npm installing it. Makes it easy to test features, hello worlds and so on.

**Pull request closed without merging**
