### PR TITLE
fix: refactor `DatePicker` component to handle `onChange` callback pr…

### PR DESCRIPTION
**Pull request by nmpavel**
---
name: Pull Request
about: Create a pull request to improve this repository
title: "Refactor DatePicker Component for Improved onChange Handling"
labels: ""
assignees: ""
---

## Description
**Linked issue**: #5044 

**Problem**
The DatePicker component had redundant ternary operations for handling the onChange callback, and default onChange implementations were not necessary. This led to potential bugs and unnecessary complexity in the component’s behavior.

**Changes**
Replaced ternary operations with optional chaining for better readability and functionality.
Removed the default onChange implementation that was redundant and not used effectively.
Updated handling of onChange and other props to ensure correct behavior.

## To reviewers
Please review the changes to ensure that the DatePicker component now handles the onChange callback correctly and that the code is clean and well-tested. Feedback on the updated behavior and any edge cases is appreciated.

## Contribution checklist
- [ Yes] I have followed the [contributing guidelines](https://github.com/Hacker0x01/react-datepicker/blob/main/CONTRIBUTING.md).
- [ No] I have added sufficient test coverage for my changes.
- [ Yes] I have formatted my code with Prettier and checked for linting issues with ESLint for code readability.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you look into the merge conflict?

**Comment by nmpavel** [comment]
> This is a significant readability improvement; bravo! The dropping of the (empty) default func `DatePicker.defaultProps.onChange` is especially helpful. Without major logic changes, I presume the existing test coverage is still passing. Looks solid.
> 
> Image of Dylan F **Dylan F**
> 
> Reviewed with ❤️ by [PullRequest](https://www.pullrequest.com)

THank you very much for your support ,it's really inspirational

**Comment by nmpavel** [comment]
> Can you look into the merge conflict?

done

**Comment by laug** [comment]
This might be a duplicate of #5045 (great minds think alike!) that was merged very recently. After your merge commit, the diff looks empty.

**Comment by martijnrusschen** [comment]
yes this seems unnecessary, please confirm this is indeed what's left over.

**Pull request closed without merging**
