### PR TITLE
CSS refactor

### PR DESCRIPTION
**Pull request by martijnrusschen**
Proposal as discussed in #388

### CODE REVIEW

**Comment by martijnrusschen** [comment]
This is probably a breaking change since people are relying on our classes.

**Comment by dmnd** [comment]
I'd also be happy with this :+1:

**Comment by martijnrusschen** [comment]
Do we like this new format? I'll rebase and merge this if we like it. (lets keep the input field styling discussion out of this PR)

**Comment by rafeememon** [comment]
I think we should go for it. And yep, addressing the field styling separately in #396

**Comment by rafeememon** [comment]
LGTM :+1:

**Comment by pinturic** [comment]
I still have a question about this: I have 4 calendars in the page and I want them to have different styles. Since the "react-datepicker" className is not editable (ora at least configurable to be addictive)  there is no chance for the 4 calendars to have different styles. Am I correct ?

**Comment by rafeememon** [comment]
Same as #377

Seems reasonable to add the `calendarClassName` prop. PRs to this effect are welcome

**Comment by pinturic** [comment]
There was one #387 as far as I know.

**Comment by rafeememon** [comment]
Yep and see the discussion there for why it wasn't merged

**Comment by pinturic** [comment]
to tell the truth it is not clear what and how to overcome the situation. In my opinion it should be enough if the className is "additive" so that nothing actually present breaks and the other added class is enough from outside to set the style.

**Comment by rafeememon** [comment]
Yep, that's what a PR implementing this should do

**Comment by pinturic** [comment]
okay perfect

**Pull request merged**
