### PR TITLE
Support autoComplete prop

### PR DESCRIPTION
**Pull request by lbntly**
For issue https://github.com/Hacker0x01/react-datepicker/issues/465

### CODE REVIEW

**Comment by rafeememon** [comment]
Thanks @lbntly, LGTM.  I think ideally we will pass all props from the `<DatePicker>` into the `<input>` so that we automatically support all possible attributes, but unfortunately we're a couple refactors away from that

**Comment by technificentConsulting** [comment]
Is this change live?  adding autocomplete="false" does not seem to work.

**Comment by leahjlou** [comment]
@technificentConsulting Did you try camelcase `autoComplete`? I also know sometimes different browsers handle this weird.

**Comment by technificentConsulting** [comment]
@leahjlou thank you and yes I've tried that as well.  Doesn't seem to get carried forward when converted to a div :(

**Comment by moeloubani** [comment]
> @leahjlou thank you and yes I've tried that as well. Doesn't seem to get carried forward when converted to a div :(

try autoComplete='off'

**Comment by Divinare** [comment]
autoComplete='off' doesn't seem to work. Also it seems like there is just autoComplete prop added but nothing is done with it.

**Comment by ultrinnan** [comment]
autoComplete="off" works as expected

**Pull request merged**
