### PR TITLE
issue #1230 - handleChange arguments checks

### PR DESCRIPTION
**Pull request by cklab**
- #1230 check the handleChange arguments before using it as en event object

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Could you perhaps add a test to make sure this won't break again?

**Comment by cklab** [comment]
@martijnrusschen Sure. I'm not sure if there's a better way to create these tests other than creating the custom inputs necessary to provide the `handleChange` with the modified arguments. I'll throw something up and feel free to make additional suggestions.

**Comment by cklab** [comment]
see #1255 for updates on the failed test

**Comment by cklab** [comment]
@martijnrusschen I'm not sure how code coverage is detected as having gone down. The new code is fully covered from what I can tell. Showing an increase on local tests. Any insight?

**Comment by martijnrusschen** [comment]
Looks good. Thanks!

**Pull request merged**
