### PR TITLE
add types

### PR DESCRIPTION
**Pull request by yuki0410-dev**
## Description
**Linked issue**: #4587

**Problem**

**Changes**
- Based on [@types/react-datepicker](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-datepicker), incorporating changes from v6.3.0 
    - add types (d.ts)
    - add test
    - add CI
    - fix md

## To reviewers
Merging and releasing this PR will allow react-datepicker type completion to work without installing @types/react-datepicker.
You will also see the TS icon (painted blue) on npmjs.com.

## Contribution checklist
- [x] I have followed the [contributing guidelines](https://github.com/Hacker0x01/react-datepicker/blob/main/CONTRIBUTING.md).
- [x] I have added sufficient test coverage for my changes.
- [x] I have formatted my code with Prettier and checked for linting issues with ESLint for code readability.

### CODE REVIEW

**Comment by yuki0410-dev** [comment]
Thanks for the review.

> My only other suggestion would be to find any instances in the README or elsewhere (e.g., documentation) that involve notes on contributing, and mention that TypeScript types should be updated when making relevant changes. A good example of this is actually your recent PR (https://github.com/Hacker0x01/react-datepicker/pull/4553).

I agree and will edit the md file.

> The primary maintainers of this repository will need to have the final say on supporting TypeScript at this level. I think it seems like a beneficial addition to the project, but we will have to wait for their feedback before finalizing this.

I agree with you.
I would be happy if the main maintainer of this repository would understand the advantages and disadvantages of this PR and adopt it.

**Comment by martijnrusschen** [comment]
@yuki0410-dev I'm not an expert, but I understand the benefits of supporting this. Is there any reason why these definitions are also maintained in a separate repo like you linked? I guess that's the same of what we're now adding in this repo.

**Comment by yuki0410-dev** [comment]
@martijnrusschen 
Thank you for your understanding regarding TS support.

When this PR is released, users of later versions will no longer need to use @types/react-datepicker. However, the current version of @types/react-datepicker must be retained for users of versions prior to that release. (No further updates will be made.)

Initially there is no difference between the two repositories, but each time a parameter such as Props is added in this repository, it will be reflected in the types in this repository, and the difference between the two repositories will become larger and larger.

In this case, we are adding the type usePointerEvent as an example.
https://github.com/Hacker0x01/react-datepicker/pull/4592/commits/363cbb6b6abeb96e15d18f70e91d4353ddfc973a

**Comment by martijnrusschen** [comment]
Thanks, will wait for the recommended updated.

**Comment by yuki0410-dev** [comment]
@martijnrusschen 
Thank you for your understanding.
I will make the corrections pointed out by linter and add the documentation.

**Comment by yuki0410-dev** [comment]
I did CI tweaks, Lint error handling, and md file corrections.

**Comment by yuki0410-dev** [comment]
Sorry, but I'm going to have to rethink the idea once and I'll make it a draft.

**Comment by mirus-ua** [comment]
This is a bold idea, but maybe we should consider adopting TS instead of just merging the repo with `.d.ts`? 

This is almost impossible to do at once, but with a proper community road map, we can do it for all files individually. Moreover, the most important part is the datepicker itself, and docs and even tests can stay written in js for any amount of time

**Comment by martijnrusschen** [comment]
Yes agree, I'm open to it but don't have the time to get this going. Open to suggestions.

**Comment by mirus-ua** [comment]
What path I see:
- create an issue similar to the mui team https://github.com/mui/material-ui/issues/41273
- prepare rollup and the rest tools to work with typescript files 
- from my experience, we should adapt ts from small modules to the bigger ones

**Comment by mirus-ua** [comment]
I can prepare a draft of the migration issue

**Comment by martijnrusschen** [comment]
@mirus-ua sounds good!

**Comment by mirus-ua** [comment]
@martijnrusschen here is the draft, let's discuss it inside the issue https://github.com/Hacker0x01/react-datepicker/issues/4700

**Comment by yuki0410-dev** [comment]
#4700 is supported so that the type definitions will be output, and this PR will be closed.

**Pull request closed without merging**
