### PR TITLE
remove extra div

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by prayerslayer** [comment]
I know, but it's there for a reason :grin: (As you can tell by the breaking tests.)

**Comment by bertho-zero** [comment]
There is no valid reason why an extra div should be added, it is a resolvable technical limitation. https://github.com/FezVrasta/react-popper/issues/79

**Comment by prayerslayer** [comment]
Yeah, I wasn't referring to any technical reason. Looking forward to see it fixed :)

**Comment by bertho-zero** [comment]
I guess it's not going to be easy, I'll try. :grin:

**Comment by martijnrusschen** [comment]
How're things going?

**Comment by bertho-zero** [comment]
@prayerslayer @martijnrusschen It works well with the same test using enzyme.

**Pull request merged**
