### PR TITLE
fix-unsafe-lifecycles

### PR DESCRIPTION
**Pull request by colinrcummings**
- change componentWillReceiveProps to componentDidUpdate
- update .eslintrc

### CODE REVIEW

**Comment by colinrcummings** [comment]
Addresses https://github.com/Hacker0x01/react-datepicker/issues/1367.

**Comment by Blackop778** [comment]
Is there any update on the status of this PR?

**Comment by Blackop778** [comment]
@colinrcummings Friendly poke for update on this PR

**Comment by colinrcummings** [comment]
cc @aij

**Comment by martijnrusschen** [comment]
Sorry, didn't catch this as it was failing some checks. Merged it now!

**Comment by boatcoder** [comment]
If this was merged, why am I still seeing the warnings?

**Pull request merged**
