### PR TITLE
Upgrade popper

### PR DESCRIPTION
**Pull request by martijnrusschen**
Migration guide: https://popper.js.org/docs/v2/migration-guide/

ref https://github.com/popperjs/react-popper/pull/333

### CODE REVIEW

**Comment by martijnrusschen** [comment]
@prayerslayer Any chance you can take a look at this?

**Comment by ksocha** [comment]
Hi!
Any chance this gets merged soon?

**Comment by martijnrusschen** [comment]
I need some help testing the changes. Since this is a major upgrade we need to be careful not breaking any existing functionality.

**Comment by czabaj** [comment]
@martijnrusschen anything I can help with? Just forked the repo to bump react-popper and realized, that this PR already exists. So, how can I serve you?

**Comment by martijnrusschen** [comment]
> @martijnrusschen anything I can help with? Just forked the repo to bump react-popper and realized, that this PR already exists. So, how can I serve you?

I did a first pass on this, but it seems it's not working yet. Feel free to add to this, or create your own PR if you can get this working. Would be great to have this upgraded to the latest version.

**Comment by martijnrusschen** [comment]
Completed in https://github.com/Hacker0x01/react-datepicker/pull/2626

**Pull request closed without merging**
