### PR TITLE
Fix doc-site example for custom input

### PR DESCRIPTION
**Pull request by robations**
Hello! I changed the example code for the doc site, which should answer #2497.

This was based on the example provided by @YanaLugina, and was tested working in my own project.

I read through the contributing guidelines etc but let me know if there's anything I've missed or should add.

Rob.

### CODE REVIEW

**Comment by robations** [comment]
> `React` is not defined

Will have to take another look. None of these example seem to use imports, I assumed React was in context for jsx.

**Comment by YanaLugina** [comment]
> Will have to take another look. None of these examples seem to use imports, I assumed React was in context for jsx.

yes, React need imported in the context above, in the same place as the DatePicker itself. Or, if used React version >= 17.0.0 need import {forwardRef} from ‘react’

**Comment by drews256** [comment]
I'll bump this PR. It should definitely be in the docs.

**Comment by robations** [comment]
Thanks for the reminder @drews256, will try to take a look at the weekend. I thought I'd already submitted a fix to be honest #brainProblems

**Comment by drews256** [comment]
I actually wanna bring this backup. I did use forwardRef like the changes here suggest and while it eliminated the ref error I was unable to get any sort of onClick callback to fire on my customInput. Have you guys seen this issue? If you haven't seen it, I may try to reproduce it in a small example and share it. After switching to a class-based component everything worked perfectly.

**Comment by robations** [comment]
@drews256 IIRC, adding forwardRef fixed any issues for me

**Pull request merged**
