### PR TITLE
Range selection highlighting

### PR DESCRIPTION
**Pull request by gpoole**
This change adds classes to allow highlighting the days between the currently hovered date and an already selected start or end date in the ranged datepicker.

I've added tests for all the cases I could think of, but there are potentially some I've missed so I'm happy to add more if needed.

### Examples

Selecting a start date before the selected one
screen shot 2016-09-06 at 5 28 33 pm

Selecting the end date after the selected one
screen shot 2016-09-06 at 5 28 38 pm

Selecting a start date after the selected one
screen shot 2016-09-06 at 5 29 25 pm

Selecting an end date before the selected one
screen shot 2016-09-06 at 5 29 31 pm

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Awesome!

**Comment by gpoole** [comment]
@martijnrusschen when are you planning your next release? I'm hoping to start using this feature in one of my projects.

**Comment by martijnrusschen** [comment]
Done!

**Comment by gpoole** [comment]
Awesome thank you!

**Pull request merged**
