### PR TITLE
Optionally wrap the popper element with a user-supplied container

### LINKED ISSUE #969: Datepicker behavior inside container with overflow: scroll
Had a problem somewhere between 0.47 and 0.52 that I believe might have been caused by the transition to tether. 

Our datepicker was in a container that was overflow:scroll, and in the old incarnation (0.47) it was fine because the calendar widget part got appended to body, but now it stays with the input dialog inside the container and was subsequently affected by the overflow (which makes sense from a CSS point of view, but not as useful for the calendar to go over the top). 

Now I can probably remove the overflow scroll as this may be intended behavior (but for people who cannot remove this, but would still like the old behavior), or perhaps I can change some options from: https://hacker0x01.github.io/react-datepicker/#example-20 to affect a better solution.

Or perhaps

Thanks,

### PR DESCRIPTION
**Pull request by pmacmillan**
react-popper will place the popover in the same constraints as the
parent div. For cases where the parent div is somehow constrained -- a
scrollable div -- the popper will appear inside the div and will be
constrained by it to.

There are cases where you want the popover to be unconstrained it's
parent. To do this, you must place the popover in a container outside of
the constrained container.

demo: https://codesandbox.io/s/1ozy5ol5vl

Adding a popperContainer would allow a user to implement the following

  function CalendarContainer (props) {
    const containerId = document.getElementById('container-outside-root')

    return (
      <Portal container={containerId}>
        {props.children}
      </Portal>
    )
  }

  // somewhere else

  <DatePicker ... popperContainer={CalendarContainer} />

Which will then permit rendering the control inside the div and the
calendar outside the div (which the popper library will connect through
the magic of javascript)

### CODE REVIEW

**Comment by pmacmillan** [comment]
Fix #969

**Comment by iamandrewluca** [comment]
I am using `reactstrap`. Just added this
```js
import Portal from 'reactstrap/lib/Portal'
// ...
<DatePicker
  // ...
  popperContainer={Portal}
  // ...
/>
```
creation and removal of nodes are handled by `Portal`. I laughed. Thanks!

**Comment by Rafael-Ramblas** [comment]
First, thanks for the PR, it really helped me, but, when i open the date-picker inside a modal, it renders the picker under the modal, so its clipped where the modal ends.
captura de tela de 2018-09-12 15-09-51

**Comment by thiagofront** [comment]
works fine

``` jsx
import ReactDOM from 'react-dom';

const $el = document.querySelector('#yourElement');

const PopperContainer = ({ children }) => (
  ReactDOM.createPortal(
    children,
    $el,
  )
);

<DatePicker
  {...anotherConfigs}
  popperContainer={PopperContainer}
/>
```

**Comment by activenode** [comment]
> works fine
> 
> ```js
> import ReactDOM from 'react-dom';
> 
> const $el = document.querySelector('#yourElement');
> 
> const PopperContainer = ({ children }) => (
>   ReactDOM.createPortal(
>     children,
>     $el,
>   )
> );
> 
> <DatePicker
>   {...anotherConfigs}
>   popperContainer={PopperContainer}
> />
> ```

What I was searching for.

**Pull request merged**
