### PR TITLE
react-onclickoutside discontinued support for usage as mixin

### PR DESCRIPTION
**Pull request by balsamiqstefano**
Addresses the following error when using React v15: `Invariant Violation: ReactClass: You're attempting to use a component class or function as a mixin. Instead, just use a regular object`

### CODE REVIEW

**Comment by balsamiqstefano** [comment]
Sorry, I can't figure out why the tests are failing.

```
Uncaught TypeError: (0 , _reactOnclickoutside2.default) is not a function
  at /Users/stefano/projects/react-datepicker/test/index.js:34799 <- webpack:///src/year_dropdown_options.jsx:9:967
```

The code seems to work though.

**Comment by rafeememon** [comment]
The dependency version needs to be bumped as well; the API change happened in v5 but we depend on `^4.8.0` (handy semver calculator: http://semver.npmjs.com/)

**Comment by balsamiqstefano** [comment]
Doh, of course!

So, ok, I tried bumping up the revision, but now a whole bunch of other tests fail. :-(

**Comment by martijnrusschen** [comment]
Can you post the log here? Or push the change and let Travis build it?

**Comment by rafeememon** [comment]
@balsamiqstefano, any luck here?  Would love to get this in so that the onclickoutside dependency doesn't fall too far behind

**Comment by valerybugakov** [comment]
Would be great to have this merged!

**Comment by rafeememon** [comment]
Closing for lack of activity

**Comment by plentz** [comment]
#536

**Pull request closed without merging**
