### PR TITLE
added renderChildrenForDate prop

### PR DESCRIPTION
**Pull request by aybb**
Add prop `renderChildrenForDate` which will allow to render any component in addition to day of month.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Can you expand a bit on the use case here?

**Comment by aybb** [comment]
@martijnrusschen I just need to add text for date. See screenshot.

**Comment by klis87** [comment]
Very nice idea, I also need this to show some tooltips for given dates, with customer renderer this would be trivial.

**Comment by martijnrusschen** [comment]
Can we get the merge conflicts resolved so I can merge this?

**Comment by jRichardeau** [comment]
I also need this to customize cell content !
But why a render prop that only adds children to date ? I think a better idea would be to have a render prop for all date cell, isn't it ?

**Pull request closed without merging**
