### PR TITLE
Better Popover Triangle Orientation

### PR DESCRIPTION
**Pull request by malectro**
This allows the triangle to be positioned relative to the right side of the popover if the user passes `popoverAttachment="right"` as a prop.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Thanks!

**Comment by malectro** [comment]
Great lib. Glad to help out!

**Comment by lukastong** [comment]
@malectro i used `popoverAttachment="right"` as a prop, but threw error `Failed prop type: Invalid prop `attachment` of value `right` supplied to `TetherComponent`, expected one of ["top left","top center","top right","middle left","middle center","middle right","bottom left","bottom center","bottom right"].`
i m using version 0.29.0(the latest version download from npm)
did V.0.51.0 published on npm?

**Comment by martijnrusschen** [comment]
According to https://www.npmjs.com/package/react-datepicker 0.51.0 is the latest published version.

**Comment by lukastong** [comment]
@martijnrusschen thx~ but why can't i V0.51.0? even if i use `npm install react-datepicker@0.51.0 --save`...

**Pull request merged**
