### PR TITLE
Display custom header when monthsShown prop is bigger than 1

### LINKED ISSUE #2351: bug?: when using renderCustomHeader and monthsShown props just show one header
**Describe the bug**
when using renderCustomHeader and monthsShown props just show one header

**To Reproduce**

```js
() => {
  const [startDate, setStartDate] = useState(new Date());
  const years = range(1990, getYear(new Date()) + 1, 1);
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];
  return (
    <DatePicker
      renderCustomHeader={({
        date,
        changeYear,
        changeMonth,
        decreaseMonth,
        increaseMonth,
        prevMonthButtonDisabled,
        nextMonthButtonDisabled
      }) => (
        <div
          style={{
            margin: 10,
            display: "flex",
            justifyContent: "center"
          }}
        >
          <button onClick={decreaseMonth} disabled={prevMonthButtonDisabled}>
            {"<"}
          </button>
          <select
            value={getYear(date)}
            onChange={({ target: { value } }) => changeYear(value)}
          >
            {years.map(option => (
              <option key={option} value={option}>
                {option}
              </option>
            ))}
          </select>

          <select
            value={months[getMonth(date)]}
            onChange={({ target: { value } }) =>
              changeMonth(months.indexOf(value))
            }
          >
            {months.map(option => (
              <option key={option} value={option}>
                {option}
              </option>
            ))}
          </select>

          <button onClick={increaseMonth} disabled={nextMonthButtonDisabled}>
            {">"}
          </button>
        </div>
      )}
      selected={startDate}
      monthsShown={2}
      onChange={date => setStartDate(date)}
    />
  );
};

```

**Expected behavior**
show all custom header

**Screenshots**

current behavior

image

expected behavior

image

### PR DESCRIPTION
**Pull request by relwiwa**
Custom header now gets rendered for every month when monthsShown prop > 1;

Introduced customerHeaderCount prop to be able to conditionally render and adapt content in custom header, e.g. manipulate the displayed month value based on the date and customHeaderCount props

fixes #2351

### CODE REVIEW

**Comment by relwiwa** [comment]
@martijnrusschen: I adapted the commit so that the time.jsx files test coverage got back to its previous state. Please merge this PR or leave comment if there are reasons not to merge it. Thank you.

**Comment by murariamar** [comment]
hi @relwiwa in which version of react-datepicker can I get this change?

**Comment by relwiwa** [comment]
@murariamar It got merged some days ago, so I guess it will be in the next release

**Comment by murariamar** [comment]
@relwiwa thanks for the prompt response newer version has been published, I could see custom header rendered for both the calendar inputs (as monthShown={2} in my example ) trouble is how do I customise different headers for each calendar displayed, at the moment my code looks as below for `renderCustomHeader`

```
 renderCustomHeader={({
            decreaseMonth,
            increaseMonth,
            prevMonthButtonDisabled,
            nextMonthButtonDisabled
          }) => (
              <div className='ld-sc-ui-date-picker--header'>
                <Button variant='icon-regular' onClick={decreaseMonth} disabled={prevMonthButtonDisabled} startIcon={<ChevronLeftIcon size='small'/>}/>
                <Button variant='text-only' onClick={handleMonthClick} >{`${month} ${year}`}</Button>
                <Button variant='icon-regular' onClick={increaseMonth} disabled={nextMonthButtonDisabled} startIcon={<ChevronRightIcon size='small'/>} />
              </div>
          )}
```

**Comment by murariamar** [comment]
Hi @relwiwa, thanks for the prompt response, version has been bumped up now, any idea how to render different custom headers for each calendar rendered, my code for `renderCustomHeader` looks as below, trouble I am noticing now is each calender renders same custom header, I want to render different header for each example: Month different for each, etc

Please let me know if I need to create an issue for the same
```
renderCustomHeader={({
            date,
            decreaseMonth,
            increaseMonth,
            prevMonthButtonDisabled,
            nextMonthButtonDisabled
          }) => (
            <div className='ld-sc-ui-date-picker--header'>
              {console.log('date.....', date)}
              <Button variant='icon-regular' onClick={decreaseMonth} disabled={prevMonthButtonDisabled} startIcon={<ChevronLeftIcon size='small'/>}/>
              <Button variant='text-only' onClick={handleMonthClick} >{`${MONTHS[date.getMonth()]} ${date.getFullYear()}`}</Button>
              <Button variant='icon-regular' onClick={increaseMonth} disabled={nextMonthButtonDisabled} startIcon={<ChevronRightIcon size='small'/>} />
            </div>
          )}
```

**Comment by relwiwa** [comment]
@murariamar I introduced the new prop customHeaderCount. Like this you know which custom header is currently rendered and based on it, you can manipulate the content, e.g display month for first custom header, month + 1 for second custom header, etc.

**Comment by murariamar** [comment]
Thanks @relwiwa for the quick response, looks its not updated in prop type or am I missing something

**Comment by relwiwa** [comment]
@murariamar I think @types/react-datepicker is not yet updated, so need to use ts-ignore for now

**Comment by murariamar** [comment]
ok, thanks again

**Pull request merged**
