### PR TITLE
Prevent 'open' from being called when datepicker is shown inline.

### PR DESCRIPTION
**Pull request by Amauris**
Currently there's an issue with inline calendar, where picking a date, not belonging to the current month, will trigger the calendar to render itself with the wrong month showing. 
This is caused because datepicker.jsx's 'open' is re-writing handleSelect's 'preSelection' modification.

Change includes preventing 'open(false)' from being called if datepicker is an inline calendar.

### CODE REVIEW

**Comment by cozmo** [comment]
What would it take to get this PR merged? This is causing us to have to lock ourselves to an older version which is suboptimal.

**Comment by janbuerling** [comment]
What about this error? Is a time near the fixes in sight or is there a workaround?

**Comment by alex-shamshurin** [comment]
Please exclude `build.js` from the commit and resolve other conflicts.

**Comment by martijnrusschen** [comment]
Sorry I merged another PR that's conflicting with yours. Can you double check your changes and rebase against the most recent master? I'll merge it directly afterwards.

**Comment by martijnrusschen** [comment]
Closing this since it's a duplicate of #941 941

**Pull request closed without merging**
