### PR TITLE
Adding error emitter for user input error

### PR DESCRIPTION
**Pull request by buhuitou**
This pull request is to address the needs to manage keyboard input error outside date picker component by emitting validation error when Enter, Tab, or Esc is pressed.

### CODE REVIEW

**Comment by aij** [comment]
Why only when Enter, Tab, or Esc are pressed?

**Comment by buhuitou** [comment]
Hi! Thanks for your question.

As I understand, Enter, Tab or Esc key press gives the signal that user typing-in is ended hence eventual error events should be emitted.

I hope my answer is clear.

**Comment by aij** [comment]
@buhuitou Some users like to (over)use a mouse. It seems weird to handle Tab differently from clicking to the next field.

Most users also have a multi-tasking OS these days. I don't know whether switching to a different app should be considered the end of typing or just a pause in typing though. I expect there is no right answer there, and it will be wrong no matter what we do.

**Comment by buhuitou** [comment]
@aij I think your points are reasonable.

As to the first point, I definitely agree that the event should be emitted when the field loses focus instead of on Tab pressed.

As to the second point, I think the proposal implements only optional event and they may be simply ignored when not desired. For this reason, they are not intrusive but give flexibility of control.

By the way, at least on Mac, Cmd-Tab does not trigger Blur event. I think it's the same on Linux but I am not sure on Windows.

If you agree, I can adjust the implementation for the first point.

**Comment by martijnrusschen** [comment]
@aij Thoughts? Good to merge?

**Comment by aij** [comment]
@martijnrusschen Sure.

**Comment by martijnrusschen** [comment]
@buhuitou This should be good to merge when the merge conflicts are resolved. Can you take a look, so that we can merge this one?

**Comment by martijnrusschen** [comment]
Closing due inactivity.

**Pull request closed without merging**
