### PR TITLE
Added highlightDates2 and highlightDates3 ranges

### PR DESCRIPTION
**Pull request by alex-shamshurin**
Sometimes we need diffrent highlighted date ranges with diffrent styles. I added `highlightDates2` and `highlightDates2` props. It can be very useful to apply different styles.

### CODE REVIEW

**Comment by alex-shamshurin** [comment]
Ok, I think it might be an array. I'll do it.

**Comment by rafeememon** [comment]
Cool, keep in mind that the API will need to be backwards-compatible

**Comment by alex-shamshurin** [comment]
Yep, `this.highlightedDates` may be an array of `moment` or multidimensional array of `moment`s

**Comment by rafeememon** [comment]
That could work; it's not obvious how you might specify the class name for the additional date ranges in a sane way, but maybe you can find something that works well =)

**Comment by alex-shamshurin** [comment]
I think `className + arrayIndex`, like ''react-datepicker__day--highlighted2''. Beside this, have no idea how to make it better.

**Pull request closed without merging**
