### PR TITLE
Fixed doc

### PR DESCRIPTION
**Pull request by nimzco**
There was a typo in the doc

was `showTodayButton` instead of `todayButton`

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Thanks!

**Comment by tsironis** [comment]
@martijnrusschen There is the same typo in the [website](http://hacker0x01.github.io/react-datepicker/#example-3). There is a ```bundle.js``` in ```gh-pages``` branch, but I'm not sure I should mess with it!

**Comment by martijnrusschen** [comment]
I guess the examples site hasn't been deployed yet. I'll trow a release
today that should update the site too. Thanks!

**Comment by tsironis** [comment]
No worries! Congrats on the library btw, awesome work.

**Comment by martijnrusschen** [comment]
Should be fixed now!

**Pull request merged**
