### PR TITLE
Update react-onclickoutside dep

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by zslabs** [comment]
You'll probably want to run `yarn` in your PR branch so the `yarn.lock` file can be updated as well.

**Comment by Andarist** [comment]
ah yeah, done the changes from the github UI, havent noticed this project has a lockfile

fixed :)

**Comment by william57m** [comment]
Perfect, this need to be merged, I have some warnings because of that since I updated my app to React 16, thanks.

**Comment by SpencerTorres** [comment]
I hope it gets merged sometime today. My production app is using a terrible hack that increased my app bundle from about 60 to 600kb. 

Thanks for getting this PR submitted!

**Comment by zslabs** [comment]
If you need it “now now” then you could always just fork the repo with the change and add that as your dep instead - then check back in a few days.

**Comment by Andarist** [comment]
For the time being if you use npm5 you can specify package.json entry as:
```
"react-datepicker": "Andarist/react-datepicker#fix/deps"
```

It will build this project correctly inside of your `node_modules` using its dev deps and all.

**Comment by rafeememon** [comment]
Let's get this in, thanks for your work @Andarist

**Pull request merged**
