### PR TITLE
Added props for fully dynamic aria-labels

### PR DESCRIPTION
**Pull request by oscarcarlstrom**
Prefixes in aria-labels were hard coded, and some of the aria-attributes were entirely hard coded. They are now controlled by optional props, with a default value.

### CODE REVIEW

**Comment by kronkake** [comment]
Nice! This would be awesome.

**Comment by martijnrusschen** [comment]
It seems your PR is touching a lot of unrelated files. Can you reduce the files that aren't relevant to make reviewing easier?

**Comment by oscarcarlstrom** [comment]
@martijnrusschen: Yes sorry, I noticed that. Reverted the commit and pushed a new one

**Comment by martijnrusschen** [comment]
Thanks, this is great!

**Pull request merged**
