### PR TITLE
Improving accessibility

### PR DESCRIPTION
**Pull request by aldavigdis**
* Improving keyboard navigation. Now works with time picker too.
* Side-effect of keyboard navigation is now shift key needs to be held down for calendar navigation.
* Shorthand weekday names are now displayed as `abbr` tags, with full names as title.
* Using a colour with higher contrast for month navigation.
* Adding a WAI-ARIA compatible description.
* The text field now has the `aria-live="polite"` attribute, which should update screenreader users as soon as the value changes.
* The date picker popper now has the `aria-hidden` tag, making it invisible to screenreaders and assistive technologies, in order to make navigation more straightforward.
* The aria-describedby tag has been added as well as a description of the keyboard navigation etc.

### CODE REVIEW

**Comment by aldavigdis** [comment]
Two things — I see the CI is broken and I will do my best to push the required fix.

Seccondly, this PR is based on a Wordpress Gutenberg ticket. For context, see https://github.com/WordPress/gutenberg/issues/1311

**Comment by martijnrusschen** [comment]
Hi, thanks for making these changes. Seeing the size of the PR, I'll let @aij take a pass on this too.

**Comment by aldavigdis** [comment]
I can split it up into chunks as well.

**Comment by martijnrusschen** [comment]
No worries, just wanted an extra pair of eyes on this PR. No need to split up if it's up to me.

**Comment by johnsoft** [comment]
This comment is about a small part of the PR—the addition of the shift key. A big part of why we chose this datepicker was that picking a date with the arrow keys is convenient and "just works". I wouldn't want to start needing the shift key for this.

I see that the rationale is to preserve cursor movement in the textbox. But on many platforms, shift+left **selects** a character to the left of the cursor, so this change would still be hijacking native behavior. On Windows, ctrl+left moves a word to the left, and you can combine the two, etc. I don't think there's any modifier that wouldn't conflict with standard input behavior on some OS.

In my mind, standard input box behavior isn't really a focus of this component. There are others that do that well (e.g. [react-day-picker](http://react-day-picker.js.org)). It's kind of a UX decision that different datepickers have made in different ways. I also don't think the choice necessarily harms accessibility—as long as dates are being announced to the screen reader it should be clear that the arrow keys are the "primary" interface.

Hope that made sense.

**Comment by aldavigdis** [comment]
@johnsoft What I've been seeing on my side is complaints from users who claim the keyboard navigation is hijacking expected UI behaviour. Freeing direct use of the left and right arrow keys makes it possible to move the input cursor inside the associated input element and edit the value that way, without the user ever having to depend on the date picker.

**Comment by primetwig** [comment]
You could add a prop (e.g. `keyboardNavigationTarget=input/date/time` with `date` as default) for that.

**Comment by wiscow** [comment]
@aldavigdis I would have to agree with @johnsoft on his assessment of the shift key.  I was just about to start working on a PR for a slightly less invasive change which would only allow the left and right arrow key to change the date if the calendar is open.  This would allow a user to navigate the raw input without inadvertently opening up the calendar (my biggest gripe with the current state of accessibility).  The problem with the shift key is that it will have to be explained, as it will not be intuitive to a user.   Bottom line is that if the calendar is open the keyboard navigation on the calendar makes sense.  If it is not, it should be opened by a keystroke and then gain focus.   

Regardless, The improvements you have made here will keep us using this control as they are more restrictive than the current functionality.

**Comment by josecoelho** [comment]
My suggestion would be to split this PR, moving the `shift+arrow` key navigation to another PR but other improvements.

I quite like @wiscow idea of using the arrow keys to navigate only when the date picker is open.

Great contribution @aldavigdis! :)

**Comment by a2441918** [comment]
@aldavigdis Could you fix the conflicting files please?

**Comment by ben-caplan** [comment]
Requiring that the shift key be held while using up/down/left/right arrows to navigate within the calendar dialogue/drop down goes against the W3C A11y specification as seen here: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html#kbd_label_5

**Pull request closed without merging**
