### PR TITLE
Optional moment.js Part 1

### PR DESCRIPTION
**Pull request by prayerslayer**
Part 1 of https://github.com/Hacker0x01/react-datepicker/issues/382

* Moves all calls on moment or instances of moment into `date_utils`. (That I found, at least. Since most date properties are still instances of moment I might have missed some.)
* Discussable if there are too many functions and how the moment-agnostic Date API should look like.
* No efforts regarding order of functions were made, this I'll do later but I still wanted to give you the change to look at it.

After this PR I would work on replacing the actual moment instances.

### CODE REVIEW

**Comment by prayerslayer** [comment]
> I don't think we could completely remove moment while maintaining backwards compatibility

Yeah me neither, except you'd distribute separate builds for versions with and without moment. If that's not an option we'd need a flag *somewhere* to know which date utils to use.

**Comment by prayerslayer** [comment]
Any idea what could be wrong with the failing test? It seems to be occuring also on `master` (see this build https://travis-ci.org/prayerslayer/react-datepicker/builds/281940187), so I assume it's a dependency issue?

I'll continue on a branch based on this PR instead of master.

**Comment by aij** [comment]
@prayerslayer It appears to be a fragile test. It looks like it will always fail on the first 2 days of the month.

**Comment by montogeek** [comment]
Any updates on this?

**Comment by prayerslayer** [comment]
@montogeek There's this https://github.com/Hacker0x01/react-datepicker/pull/1327, but it's quite old by now, and has some blocking open questions.

**Pull request merged**
