### PR TITLE
Allow react 15

### PR DESCRIPTION
**Pull request by rafeememon**
Re #444, #464

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Depends on react-redbox. Opened a PR to support React 15: https://github.com/KeywordBrain/redbox-react/pull/52

Let see how long this takes. It this takes more than a few days, we should remove this dependency.

**Comment by rafeememon** [comment]
Need to remove `react-transform-catch-errors` as well...

**Comment by rafeememon** [comment]
This is finally ready to go!

**Comment by martijnrusschen** [comment]
Awesome! Great work!

**Pull request merged**
