### PR TITLE
Datepicker and Calendar are injectable for locale changes

### PR DESCRIPTION
**Pull request by MortalFlesh**
I needed to change locale for datepicker (and callendar).
All locale variables are injectable to datepicker component, now I can send it what to show (including moment itself, so it can have defined locale of my own).
PS: I'm not sure about compiled files - i just builded it with "grunt build" command

### CODE REVIEW

**Comment by RSO** [comment]
Awesome! This looks great, I'll see if I can get to reviewing this tomorrow, thanks for taking the time to write this PR!

**Comment by RSO** [comment]
Thanks again for this PR, there were some merge conflicts in the compiled files (sigh), so I merged it manually. Let me know if I missed anything in the merge!

I'll also see to adding a localized example to the examples (and maybe see to finally adding github pages for the examples).

**Comment by MortalFlesh** [comment]
Thanks for merging my changes. You could have just merge src files and build it again - by this you would avoid conflicts.
I tested it and it's ok! :+1: 
And will you make a tag?

**Comment by RSO** [comment]
Version 0.8 just got release by @martijnrusschen !

**Comment by MortalFlesh** [comment]
Great :) thank you

**Pull request merged**
