### PR TITLE
added onMonthChange Event

### PR DESCRIPTION
**Pull request by Matt007**
Added the ability to pass a function that handles the users month navigation.

Ex:

handleMonthChange(momentDate) {
  
  //return false in order to keep the current displayed month
  return false;
}
<Datepicker  onMonthChange={this.handleMonthChange}

### CODE REVIEW

**Comment by Matt007** [comment]
Test fails due too code formating. Im leaving it as it is as this seems time consuming - if anyone needs an onMonthChange Event feel free to pick this up :)

**Comment by martijnrusschen** [comment]
Sorry I can't approve this PR, code style is important to maintain the quality of the project. The checks are there for a reason and merging a failing PR will cause others problem creating PRs.

**Comment by Matt007** [comment]
I totally understand :)

**Comment by magsout** [comment]
@martijnrusschen the code looks good to you? (apart code style)

**Pull request closed without merging**
