### PR TITLE
updating doc to show all props in a table form

### LINKED ISSUE #880: update datepicker.md for better readibility
having a table format for the props makes it easier to read/comprehend then a linear format.

### PR DESCRIPTION
**Pull request by hozefaj**
fixes #880 

below is how the updated doc page will looks. _(image does not capture all props....but the docs has them)_

screen shot 2017-06-09 at 4 13 59 pm

### CODE REVIEW

**Comment by rafeememon** [comment]
Hey @hozefaj, thanks for the work here, but unfortunately the API docs are autogenerated, so this will be wiped out the next time a release is made.  I think a proper fix here needs to involve changing the autogeneration process.

**Comment by hozefaj** [comment]
Oh man. Can you point me to the auto generation process. I can maybe modify the code to generate a table then.

**Comment by hozefaj** [comment]
Thats 30min of work down the drain.... :(

**Comment by rafeememon** [comment]
I'm not particularly familiar with it, but the script is https://github.com/Hacker0x01/react-datepicker/blob/master/scripts/generateMarkdown.sh. It looks like it's written by Facebook and I'd generally prefer to avoid a custom solution, but maybe there is another doc generator that looks better.

**Comment by hozefaj** [comment]
Let me have a look. In general I also prefer against custom stuff. But here when I was reviewing docs I realized they can be much better in the form of a table.

**Comment by martijnrusschen** [comment]
If you're able to modify the scripts, I'm happy to take a look. We use react-docgen from Facebook to generate docs based on the proptypes.

**Comment by hozefaj** [comment]
Basically this https://github.com/Hacker0x01/react-datepicker/blob/master/scripts/generateMarkdown.sh#L47-L56 LOC needs to be updated to create a tabular format.

Only thing is that, if there is a way to add some description for some of the props. That would be useful.

**Comment by martijnrusschen** [comment]
> Only thing is that, if there is a way to add some description for some of the props. That would be useful.

See https://github.com/reactjs/react-docgen#example on how to add additional information to a prop.

**Comment by hozefaj** [comment]
@martijnrusschen @rafeememon Created #898 to update `generateMarkdown.sh`...

**Pull request closed without merging**
