### PR TITLE
feat: enhanced rollup configuration

### PR DESCRIPTION
**Pull request by mxschmitt**
I don't have much knowledge in rollup.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Let's give it a try.

**Comment by martijnrusschen** [comment]
Seeing some errors when releasing a new version:

```
➜  react-datepicker git:(master) ./scripts/release.sh patch
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info fsevents@2.0.7: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || >=11.0.0". Got "8.14.0"
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
error brotli-size@4.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.16.0". Got "8.14.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Updated 0 paths from the index
Can't find Husky, skipping post-checkout hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
v2.9.1
yarn global v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "react-docgen@4.1.1" with binaries:
      - react-docgen
✨  Done in 0.66s.
./scripts/release.sh: line 11: e: command not found
Can't find Husky, skipping pre-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Can't find Husky, skipping pre-push hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 292 bytes | 292.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote:
remote: GitHub found 1 vulnerability on Hacker0x01/react-datepicker's default branch (1 high). To find out more, visit:
remote:      https://github.com/Hacker0x01/react-datepicker/network/alerts
remote:
To https://github.com/Hacker0x01/react-datepicker.git
   f505c11..c3c0a6e  master -> master
Can't find Husky, skipping pre-push hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 164 bytes | 164.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/Hacker0x01/react-datepicker.git
 * [new tag]         v2.9.1 -> v2.9.1
+ react-datepicker@2.9.1
yarn run v1.15.2
$ cross-env NODE_ENV=production run-p build:** && run-p css:**
/bin/sh: cross-env: command not found
error Command failed with exit code 127.
```

**Comment by martijnrusschen** [comment]
`error Found incompatible module`

`$ cross-env NODE_ENV=production run-p build:** && run-p css:**
/bin/sh: cross-env: command not found`

**Comment by martijnrusschen** [comment]
My fault, running an old version of node.

**Comment by martijnrusschen** [comment]
New output:
```
npm notice 📦  react-datepicker@2.9.2
npm notice === Tarball Contents ===
npm notice 4.8kB   package.json
npm notice 3.2kB   CODE_OF_CONDUCT.md
npm notice 1.5kB   CONTRIBUTING.md
npm notice 1.1kB   LICENSE
npm notice 7.1kB   README.md
npm notice 1.9kB   SECURITY.md
npm notice 122.2kB es/index.js
npm notice 41B     src/stylesheets/datepicker-cssmodules.scss
npm notice 14.2kB  src/stylesheets/datepicker.scss
npm notice 1.0kB   src/stylesheets/mixins.scss
npm notice 790B    src/stylesheets/variables.scss
```

Doesn't look like the dist/ folder is back. Don't see the compiled CSS either.

**Comment by mxschmitt** [comment]
> New output:
> 
> ```
> npm notice 📦  react-datepicker@2.9.2
> npm notice === Tarball Contents ===
> npm notice 4.8kB   package.json
> npm notice 3.2kB   CODE_OF_CONDUCT.md
> npm notice 1.5kB   CONTRIBUTING.md
> npm notice 1.1kB   LICENSE
> npm notice 7.1kB   README.md
> npm notice 1.9kB   SECURITY.md
> npm notice 122.2kB es/index.js
> npm notice 41B     src/stylesheets/datepicker-cssmodules.scss
> npm notice 14.2kB  src/stylesheets/datepicker.scss
> npm notice 1.0kB   src/stylesheets/mixins.scss
> npm notice 790B    src/stylesheets/variables.scss
> ```
> 
> Doesn't look like the dist/ folder is back. Don't see the compiled CSS either.

for me it works when I try to execute "yarn build" strange.

**Comment by martijnrusschen** [comment]
Can you check the contents of v2.9.2? Just uploaded that one with the new output.

**Comment by mxschmitt** [comment]
> Can you check the contents of v2.9.2? Just uploaded that one with the new output.

image

**Comment by mxschmitt** [comment]
When I try to publish it via --dry, it will publish the dist folder
image

**Comment by martijnrusschen** [comment]
My hunch is that the release script is wrong:

```
#!/usr/bin/env bash

rm -rf ./node_modules ./lib ./dist
yarn

git checkout .

npm version $1

yarn global add react-docgen
e

git add .

git commit -m "Publish new API docs (automated commit)"

git push

git push --tags

npm publish

yarn run build
```

I think `yarn run build` be moved earlier in the process. Perhaps this was always working somehow because we had a publish script ran after the release script?

**Comment by mxschmitt** [comment]
Yep. Try to switch npm publish with yarn run build.

**Comment by martijnrusschen** [comment]
Seems that did the trick:
```
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 24.5kB dist/react-datepicker-cssmodules.css
npm notice 22.5kB dist/react-datepicker-cssmodules.min.css
npm notice 22.4kB dist/react-datepicker.css
npm notice 20.4kB dist/react-datepicker.min.css
npm notice 60.2kB es/index.js
npm notice 73.4kB lib/index.js
npm notice 65.0kB dist/react-datepicker.js
npm notice 65.0kB dist/react-datepicker.min.js
npm notice 4.8kB  package.json
npm notice 3.2kB  CODE_OF_CONDUCT.md
npm notice 1.5kB  CONTRIBUTING.md
npm notice 7.1kB  README.md
npm notice 1.9kB  SECURITY.md
npm notice 41B    src/stylesheets/datepicker-cssmodules.scss
npm notice 14.2kB src/stylesheets/datepicker.scss
npm notice 1.0kB  src/stylesheets/mixins.scss
npm notice 790B   src/stylesheets/variables.scss
```

**Pull request merged**
