### PR TITLE
Exposing onDayMouseEnter and onMonthMouseLeave callback

### PR DESCRIPTION
**Pull request by aviklai**
Hi,

This pull request exposes the onDayMouseEnter and onMonthMouseLeave callbacks to the users so they can act on these callbacks.

### CODE REVIEW

**Comment by aviklai** [comment]
Hi,

This pull request exposes the onDayMouseEnter and onMonthMouseLeave callbacks to the users so they can act on these callbacks.

**Comment by martijnrusschen** [comment]
Just curious, how do you see this being used?

**Comment by aviklai** [comment]
@martijnrusschen Hi, I have used this myself. My use case was that I needed to highlight x number of days after the hovered date. for example, if I hover on a date, I wanted the next 5 days to be highlighted. This pull request allows me to change the highlighted days on this event.

**Comment by martijnrusschen** [comment]
If you can resolve the merge conflict, I'm happy to merge this.

**Comment by aviklai** [comment]
@martijnrusschen Hi, done - I have resolved the conflicts.

**Pull request merged**
