### PR TITLE
add wrapperClassName and add width style 100%

### PR DESCRIPTION
**Pull request by mtiger2k**
add wrapperClassName to enable outer layout control, and set width to 100% accordingly.

### CODE REVIEW

**Comment by azizur** [comment]
Related to https://github.com/Hacker0x01/react-datepicker/issues/1040, https://github.com/Hacker0x01/react-datepicker/issues/932, https://github.com/Hacker0x01/react-datepicker/issues/1344, https://github.com/Hacker0x01/react-datepicker/issues/1208, and https://github.com/Hacker0x01/react-datepicker/issues/932

**Comment by YassienW** [comment]
Can we please get this merged? It seems like a lot of people (myself included) would really like this implemented!

**Comment by AntJanus** [comment]
Yep! I'd like this implemented as well! :)

**Comment by YassienW** [comment]
It seems highly unlikely that this is getting implemented at this point

**Pull request merged**
