### PR TITLE
Option to set number of years on year dropdown

### LINKED ISSUE #809: Year dropdown improvement ("infinite" scroll / show more than one on arrow click)
Is there a way of achieving this with the current API? So far I haven't found it and I'll probably try to implement it otherwise. 

(Thanks for building the component!)

Cheers

### PR DESCRIPTION
**Pull request by caffeine-based-lifeform**
Fixes #809

### CODE REVIEW

**Comment by oneRice** [comment]
Hello, what's the status of this PR? I really need it quick.

**Comment by caffeine-based-lifeform** [comment]
* Fixed conflicts.
* Updated functionality to show the number passed as prop both below and above the selected date (previously showing one less below).

**Comment by rafeememon** [comment]
@caffeine-based-lifeform @martijnrusschen Is there any practical difference between this change, and having the year dropdown respect the min/max dates?  I would prefer to stick to just having it obey min/max, because limiting the number of years is effectively specifying a min and max.

**Comment by caffeine-based-lifeform** [comment]
Our team came across this problem when we intended to use the datepicker to allow the users to specify a birthdate. Since clicking on the arrows only displays one more item in the list, it would be a problem to select a date far in the past. 
By passing the min/max as a prop we can set it to a normal human lifespan and avoid this issue.

I believe it will still obey the min/max dates as default, so it shouldn't be a problem to continue the normal use of the components.

**Comment by rafeememon** [comment]
Got it, I think I misunderstood the purpose of this PR, apologies.

**Pull request merged**
