### PR TITLE
Calendar refactor, remove DateUtil

### PR DESCRIPTION
**Pull request by rafeememon**
This PR refactors the components comprising the calendar into things that are more semantic and testable, and also removes the `DateUtil` abstraction. (#290)

### CODE REVIEW

**Comment by RSO** [comment]
Awesome stuff! This looks pretty much ready to go. Few concerns: 
- aren't we losing test coverage?
- it seems easy to miss a `.clone` call on moment. Something like moment/moment#1754 would be awesome, but I'm not sure how we could enforce this now. Thoughts?

**Comment by rafeememon** [comment]
Hey @RSO, thanks for taking a look.

* I suppose we do lose test coverage, but it is mostly just from removing the moment wrapper methods and their tests.  Now that this uses moment directly we don't need to re-test moment.  More tests can (and should) be added to test the things that used these.
* Agreed that it's easy to miss a `.clone` call, and unfortunately I don't have a good answer other than being hypervigilant in PRs =(  Maybe @martijnrusschen has thoughts here

**Comment by martijnrusschen** [comment]
> Agreed that it's easy to miss a .clone call, and unfortunately I don't have a good answer other than being hypervigilant in PRs =( Maybe @martijnrusschen has thoughts here

Yep agree. Not sure if it's possible to write a linter for this, but that could help in this case. Reading up on the discussion in moment/moment#1754, it looks like https://github.com/WhoopInc/frozen-moment could help here. Did you consider this? (or am I missing the point here? :) )

**Comment by RSO** [comment]
No, I wouldn't go for a moment fork, that would defy the purpose of having moment (and we would need to re-introduce DateUtil ;-)). Okay, @rafeememon this PR looks good to me. I'll leave the merging to you. Agree that we need to be looking out for possible `.clone` mistakes.

**Comment by martijnrusschen** [comment]
Okay I'm convinced :)

**Comment by rafeememon** [comment]
A linting rule is an interesting idea.  I started putting a rule together here: https://github.com/rafeememon/jscs-moment-immutability  I'll put the finishing touches on it and integrate it here tomorrow.

**Comment by rafeememon** [comment]
Got the rule working.  I'll make a separate PR to add it in.

**Pull request merged**
